doc/administrator/galaxy/pipelines/mentalist/index.md, doc/administrator/galaxy/pipelines/test/mentalist/mentalist.ga, src/main/resources/ca/corefacility/bioinformatics/irida/model/enums/workflows/MLSTMentalist/0.1.8/irida_workflow.xml, src/main/resources/ca/corefacility/bioinformatics/irida/model/enums/workflows/MLSTMentalist/0.1.8/irida_workflow_structure.ga
=> Update MentaLiST-0.1.8 galaxy tool

src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysisController.java, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/dto/AnalysisProjectShare.java, src/main/webapp/resources/js/pages/analysis/analysis.js
=> Fix sharing analysis with a project

src/main/java/ca/corefacility/bioinformatics/irida/ria/web/linelist/LineListController.java, src/main/webapp/pages/samples/sample_edit.html, src/main/webapp/resources/js/pages/projects/linelist/reducers/fields.js, src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/LineListControllerTest.java
Signed-off-by: Josh Adam <josh.adam@canada.ca>
=> Fixed issue where sample name and checkbox fields were editable

doc/administrator/web/config/irida.conf
Fixes an out-of-date line in our documentation.
No issue.
=> Fixed up info in docs

CHANGELOG.md, src/main/webapp/pages/projects/project_samples.html, src/main/webapp/pages/samples/sample_files.html, src/main/webapp/pages/templates/galaxy.tmpl.html, src/main/webapp/resources/js/modules/cart/irida.cart.js
Fixed the galaxy export from the project/samples page.  This should be tested by running a galaxy server with the irida-galaxy-importer tool and attempting to export data from both the project/samples page and from the cart.
N/A
=> Fixed galaxy export from project/samples

CHANGELOG.md, src/main/webapp/package.json, src/main/webapp/resources/js/pages/projects/samples/project-samples.js, src/main/webapp/resources/js/pages/remote-apis/remote-apis.js, src/main/webapp/yarn.lock
Updated package.json to use jquery version 3.3.1 to fix security vulnerability.
=> Fix jquery vulnerability

doc/user/tutorials/uploader-tool/index.md
Created a header for the new command line uploader.
Also fixed the hard link to the miseq uploader download, and pointed it to the releases page so that it won't be out of date when new releases come out.
=> linked new uploader in the docs

CHANGELOG.md, src/main/webapp/resources/js/pages/analyses/analysis-outputs-table.js, src/main/webapp/resources/js/pages/analysis/controllers/bio_hansel.js, src/main/webapp/resources/js/pages/projects/linelist/components/Table/renderers/IconCellRenderer.jsx, src/main/webapp/resources/js/pages/projects/project-users-groups.js, src/main/webapp/resources/js/pages/projects/samples-metadata-import/components/selectSampleNameColumn.component.js, src/main/webapp/resources/js/pages/remote-apis/remote-apis.js
Fixes some minor javascript issues that were flagged during code quality analysis.
N/A
=> JavaScript code cleanup

.travis.yml
This pull request is only so the travis tests kick off.
=> try travis tests with xenial

src/main/webapp/resources/js/components/SampleDetails/SampleDetails.jsx, src/main/webapp/resources/js/components/SampleDetails/SampleDetailsLoader.jsx, src/main/webapp/resources/js/components/SampleDetails/index.js, src/main/webapp/resources/js/pages/cart/components/Cart.jsx, src/main/webapp/resources/js/pages/cart/components/CartSamples.jsx, src/main/webapp/resources/js/pages/cart/components/CartTools.jsx
No functional code changes are added here.  This just allows for code splitting for the initial download of the cart page.
N/A
=> Cart code splitting

src/main/java/ca/corefacility/bioinformatics/irida/ria/web/cart/CartController.java, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/pipelines/PipelineController.java, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/pipelines/dto/Pipeline.java, src/main/resources/i18n/messages_en.properties, src/main/webapp/pages/cart.html, src/main/webapp/resources/js/components/pipeline/Pipeline.jsx, src/main/webapp/resources/js/pages/cart/components/Cart.jsx, src/main/webapp/resources/js/pages/cart/components/CartSider.jsx, src/main/webapp/resources/js/pages/cart/components/CartTools.jsx, src/main/webapp/resources/sass/app.scss, src/main/webapp/webpack.config.dev.js
- Fixes redirect from a pipeline on an empty cart
- Removes never used string in the PipelineController
- Removes unused imports from the cart on the client side
N/A
=> Cart fixes

README.md, doc/index.html
Added citation of IRIDA bioRxiv paper to docs. Also added two additional badges to README.
Issue #267 
* ~[ ] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.~
=> Adding citation to docs

.travis.yml, CHANGELOG.md
Falling back to MySQL instead of mariadb for now for testing.  Having issues with installing MariaDB in travis right now.  To test just verify CI tests pass.
N/A
=> MySQL for TravisCI

src/main/webapp/resources/js/pages/projects/linelist/reducers/fields.js, src/main/webapp/resources/js/pages/projects/linelist/sagas/templates.js
Assign columns that are not icons or dates the default ag-grid text filter option.
N/A
=> Fixes issue with filters not being displayed properly

CHANGELOG.md
Fixed changelog link from 1904 to 1905.
None.
=> Fixed changlog link from 1904 to 1905

src/main/webapp/package.json, src/main/webapp/resources/js/pages/projects/linelist/components/LineList/LineListContainer.js, src/main/webapp/resources/js/pages/projects/linelist/components/Table/Table.jsx, src/main/webapp/resources/js/pages/projects/linelist/components/TableControlPanel/Columns/ColumnVisibility.jsx, src/main/webapp/resources/js/pages/projects/linelist/components/TableControlPanel/TemplatesPanel/SaveTemplateModal.jsx, src/main/webapp/resources/js/pages/projects/linelist/components/TableControlPanel/TemplatesPanel/TemplateSelect/TemplateSelect.jsx, src/main/webapp/resources/js/pages/projects/linelist/components/TableControlPanel/TemplatesPanel/TemplatesPanel.jsx, src/main/webapp/resources/js/pages/projects/linelist/reducers/fields.js, src/main/webapp/resources/js/pages/projects/linelist/reducers/templates.js, src/main/webapp/yarn.lock
Removes all dependency on ImmutableJS from the linelist page.
N/A
=> Linelist remove immutablejs templates and fields

CHANGELOG.md, src/main/webapp/resources/js/pages/projects/linelist/components/AddToCartButton/AddSamplesToCart.jsx, src/main/webapp/resources/js/pages/projects/linelist/components/LineList/LineListContainer.js, src/main/webapp/resources/js/pages/projects/linelist/components/LineList/LineListLayoutComponent.jsx, src/main/webapp/resources/js/pages/projects/linelist/components/Table/Table.jsx, src/main/webapp/resources/js/pages/projects/linelist/components/Toolbar/Toolbar.jsx, src/main/webapp/resources/js/pages/projects/linelist/reducers/entries.js
Cleans up some of the redux calls to the actual table.
N/A
=> Linelist table redux cleanup

CHANGELOG.md, src/main/webapp/bower.json, src/main/webapp/entries.js, src/main/webapp/pages/login.html, src/main/webapp/pages/template/page.html, src/main/webapp/resources/js/app.js, src/main/webapp/webpack.config.js
Changes the way angular is loaded onto the website.  Now loaded through bower, with an expose loader so that any scripts written directly on the page can still access it.
#125 
Depends on #393 
=> Remove angularjs from bower.

CHANGELOG.md, src/main/webapp/package.json, src/main/webapp/yarn.lock
Updated axios (ajax library) to fix vulnerability.
N/A
=> Updated axios to latest build to fix vulnerability

CHANGELOG.md, src/main/webapp/package.json, src/main/webapp/yarn.lock
Updated fstream to version 1.0.12 to fix security vulnerability.
=> Updated fstream to v1.0.12 to fix security vulnerability

CHANGELOG.md, pom.xml
Removed Franklin and added Deep and Jeff as developers for IRIDA.
N/A
=> Updated developers portion of pom file.

CHANGELOG.md, src/main/resources/i18n/messages_en.properties, src/main/webapp/bower.json, src/main/webapp/entries.js, src/main/webapp/package.json, src/main/webapp/pages/clients/_base.html, src/main/webapp/pages/template/page.html, src/main/webapp/resources/js/client.js, src/main/webapp/webpack.config.js, src/main/webapp/yarn.lock
Removed momentjs from the base `page.html`, removed from being added to the webpack global variables, added a webpack entry for `clients.js` so in could import webpack on its own.
N/A
Depends on PR #407 
=> Remove momentjs from being loaded on every page.

CHANGELOG.md, src/main/webapp/package.json, src/main/webapp/resources/js/components/Header/PageHeader.jsx, src/main/webapp/resources/js/components/notifications/Notifications.jsx, src/main/webapp/resources/js/modules/notifications.js, src/main/webapp/resources/js/pages/projects/linelist/components/Table/Table.jsx, src/main/webapp/resources/js/pages/projects/linelist/sagas/entries.js, src/main/webapp/yarn.lock, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/groups/GroupsPageIT.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/ProjectMembersPage.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/groups/GroupsPage.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/AssociatedProjectEditPage.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectLineListPage.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/AssociatedProjectsEditPageIT.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectMembersPageIT.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/utilities/PageUtilities.java
=> Remove noty and use ant.design notifications

CHANGELOG.md, src/main/webapp/bower.json, src/main/webapp/entries.js, src/main/webapp/pages/sequenceFiles/file_overrepresented.html, src/main/webapp/pages/sequencingRuns/run_files.html, src/main/webapp/resources/js/pages/sequence-files/overrepresented.js, src/main/webapp/resources/js/pages/sequence-files/run-files.js
Remove bower dependency on datatables.  Had to create 2 webpack entries to clean up on page code. 
N/A
Depends on #412
=> Remove bower datatables

CHANGELOG.md, doc/_includes/administrator/galaxy/setup/automated-tool-install.md, packaging/README.md
Updated documentation to use correct `shed-tools` command.
Fixes issue #428 
=> Updated docs with correct shed-tools command

src/main/webapp/package.json, src/main/webapp/yarn.lock
Updated lodash to v4.17.13 using resolutions (any package requiring lodash will pull this version at minimum.
=> Upgraded lodash to v4.17.13 using resolutions in package.json

src/main/webapp/package.json
=> updated chromedriver to 76 to be compatible with travis

src/main/java/ca/corefacility/bioinformatics/irida/repositories/analysis/submission/AnalysisSubmissionRepositoryImpl.java, src/main/webapp/package.json, src/main/webapp/pages/cart.html, src/main/webapp/resources/js/apis/pipelines/pipelines.js, src/main/webapp/resources/js/pages/analyses/analysis-outputs-table.js, src/test/resources/ca/corefacility/bioinformatics/irida/service/impl/analysis/submission/AnalysisSubmissionServiceIT_getAnalysisOutputFileInfo.xml
Changed the project analysis submission output files page to show all automated submissions instead of just the assembly and SISTR pipelines.
Also cleaned up a bit of the SQL used to generate these tables.  They had a few more joins than needed.
Part of #240
=> Analysis Output Files all automated submissions

src/main/webapp/resources/js/components/pipeline/Pipeline.jsx
Issue caused by most recent ant.design update.
N/A
=> Fix display select pipeline button on cart page.

src/main/webapp/pages/template/page.html
Removed unsed html code for the replaced angular session modal.
N/A
=> Removed old and replaced modal code.

CHANGELOG.md, src/main/webapp/resources/js/components/pipeline/Pipeline.jsx
Fixes issue with the select pipeline button on the cart page. Changes button to link.
N/A
=> Fixes issue with the select pipeline button on the cart page.

src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/ProjectsRestController.java, src/main/webapp/resources/js/apis/projects/projects.js
Fixes issue caused by the Java 11 update where the referer could not be found in the request object.
N/A
* No CHANGELOG since this is not actually a real issue yet.
=> Fixed issue where the referer could not be found in the request.

src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysesAjaxController.java, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysisController.java, src/main/webapp/entries.js, src/main/webapp/pages/analyses/analyses.html, src/main/webapp/pages/projects/analyses/pages/analyses_table.html, src/main/webapp/resources/js/pages/analyses/AnalysesPage.jsx, src/main/webapp/resources/js/pages/projects/project-analyses/ProjectAnalysesPage.jsx
Fixes issue caused by java upgrade where referer could not be found in the request object.
N/A
=> Fixes analyses listing pages

src/main/webapp/resources/js/apis/oauth/oauth.js, src/main/webapp/resources/js/components/AnalysesTable/AnalysesTable.jsx, src/main/webapp/resources/js/components/galaxy/GalaxyApp.jsx, src/main/webapp/resources/js/components/galaxy/GalaxyDetailsForm.jsx, src/main/webapp/resources/js/components/galaxy/GalaxySubmitError.jsx, src/main/webapp/resources/js/components/pipeline/Pipeline.jsx, src/main/webapp/resources/js/modules/utilities/file.utils.js
Just a quick run of prettier over entire directory to fix files that had lost some formatting.
=> Run prettier on all files to fix ones that had poor formatting.

CHANGELOG.md, src/main/webapp/bower.json, src/main/webapp/entries.js, src/main/webapp/pages/pipelines/types/generic_pipeline.html, src/main/webapp/resources/js/pages/pipelines/pipeline.launch.js
Removed ng-file-upload from bower into yarn
#125 
=> Remove ng-file-upload from bower

CHANGELOG.md, pom.xml
- Updated to new LTS version of NodeJS
- Updated to newest version of Yarn
N/A
=> Update to latest `yarn` and `node`

src/main/webapp/pages/analyses/analyses-table.html
Accidentally removed a required file for displaying analysis outputs tables
N/A
=> Re-added required template file for analyses output tables.

src/main/webapp/resources/js/components/tabs/TabPaneContent.jsx, src/main/webapp/resources/js/components/tabs/index.js
Added a TabPaneContent component to use when displaying content for a tab.
=> Added component to use inside a tab to display the content

src/main/webapp/resources/js/pages/analysis/components/Analysis.jsx, src/main/webapp/resources/js/pages/analysis/components/AnalysisError.jsx, src/main/webapp/resources/js/pages/analysis/components/AnalysisSettings.jsx, src/main/webapp/resources/js/pages/analysis/components/AnalysisSistr.jsx, src/main/webapp/resources/js/pages/analysis/components/AnalysisSteps.jsx, src/main/webapp/resources/js/pages/analysis/components/jobErrors/GalaxyJobInfo.jsx, src/main/webapp/resources/js/pages/analysis/components/jobErrors/GalaxyJobInfoTab.jsx, src/main/webapp/resources/js/pages/analysis/components/jobErrors/GalaxyParametersTab.jsx, src/main/webapp/resources/js/pages/analysis/components/jobErrors/StandardErrorTab.jsx, src/main/webapp/resources/js/pages/analysis/components/jobErrors/StandardOutputTab.jsx, src/main/webapp/resources/js/pages/analysis/components/settings/AnalysisDelete.jsx, src/main/webapp/resources/js/pages/analysis/components/settings/AnalysisDetails.jsx, src/main/webapp/resources/js/pages/analysis/components/settings/AnalysisReferenceFileRenderer.jsx, src/main/webapp/resources/js/pages/analysis/components/settings/AnalysisSampleRenderer.jsx, src/main/webapp/resources/js/pages/analysis/components/settings/AnalysisSamples.jsx, src/main/webapp/resources/js/pages/analysis/components/settings/AnalysisShare.jsx, src/main/webapp/resources/js/pages/analysis/components/sistr/CgMlst.jsx, src/main/webapp/resources/js/pages/analysis/components/sistr/Citation.jsx, src/main/webapp/resources/js/pages/analysis/components/sistr/Mash.jsx, src/main/webapp/resources/js/pages/analysis/components/sistr/SerovarPredictions.jsx, src/main/webapp/resources/js/pages/analysis/components/sistr/SistrInfo.jsx, src/main/webapp/resources/js/pages/projects/associated-projects/AssociatedProjects.jsx, src/main/webapp/resources/js/pages/projects/associated-projects/ViewAssociatedProjects.jsx
Updated react components to point to correct file for i18n utilities.
=> Updated filename

src/main/webapp/resources/js/pages/projects/associated-projects/AssociatedProjects.jsx, src/main/webapp/resources/js/pages/projects/associated-projects/ViewAssociatedProjects.jsx
This link was broken during a recent merge request.
N/A
=> Fixed broken links for i18n-utilities

CHANGELOG.md
Removed old bootstrap files that were once used for customization.  These files are now empty and not used anymore.
N/A
=> Removed empty style files (previously used for bootstrap customizations)

CHANGELOG.md, src/main/webapp/package.json, src/main/webapp/yarn.lock
Updated to version 3.26.0 of ant.design
**IMPORTANT: 🏆 3.26.0 will be the last minor version of antd v3**
N/A
=> Updated to most recent ant.design

CHANGELOG.md, src/main/webapp/resources/js/apis/analysis/analysis.js
Fixed issue with downloading multiple analysis outputs as well as viewing user analysis outputs.
#534 
#535
=> Fixed url for downloading multiple analysis outputs.

CHANGELOG.md, pom.xml
Upgraded spring to 5.2.2 bugfix release.
To test verify CI tests complete.
N/A
=> Upgraded spring to 5.2.2

CHANGELOG.md, src/main/webapp/package.json
Update to latest chromedriver for CI testing.
N/A
=> Updated to latest chromedriver

src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysisController.java, src/main/webapp/pages/analysis.html, src/main/webapp/resources/js/contexts/AnalysisContext.js, src/main/webapp/resources/js/pages/analysis/components/AnalysisSteps.jsx, src/main/webapp/yarn.lock, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectLineListPage.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/analysis/AnalysisControllerTest.java
Analysis error is marked on the correct step rather than defaulting to the "Queued" step
=> Analysis/ steps error

src/main/webapp/resources/js/components/ant.design/table-renderers.js, src/main/webapp/resources/js/pages/projects/list/ProjectsTable.jsx, src/main/webapp/yarn.lock
Removed the fixed width of the id column.  This will ensure no matter how large the id's in IRIDA get that column should not overflow.
N/A
=> Fix issue with fixed width of the id column of projects table.

src/main/webapp/yarn.lock
Fixed old yarn lock file causing angular security warning.
=> Fixed yarn lock file

src/main/webapp/resources/js/components/Header/PageHeader.jsx, src/main/webapp/resources/js/utilities/url-utilities.js
Issue seems to stem from lazy loading the css.  Since this is a very small bit of code, I have removed the lazy load from it.
N/A
=> Fixes issue where galaxy banner does not load

src/main/webapp/resources/js/utilities/url-utilities.js
Fixed issue where servlet path was being added multiple times.  This was because I removed the leading `/` before checking if that path was already there  🤦‍♂️.
N/A
=> Fixed issue where servlet path was being added multiple times.

src/main/webapp/resources/js/pages/analysis/tabular-preview.js
Fixes issue with tabular preview not displaying because I commented out the code.
N/A
=> Re-enabled tabular previews.

CHANGELOG.md, src/main/webapp/webpack.config.prod.js
Removed webpack progress to stop over logging on builds.
N/A
=> Removed webpack progress

CHANGELOG.md, pom.xml, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysesAjaxController.java, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/dto/AnalysesFilters.java, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/models/TableRequest.java, src/main/webapp/resources/js/components/ant.design/table-search-props.js, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/analysis/AnalysesUserPageIT.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/analysis/AnalysisAdminPageIT.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/analysis/AnalysesUserPage.java, src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysisAdminView.xml
Fixes bug where analyses table name filtering was only occurring client side.
N/A
=> Hotfix ant table filtering

src/main/webapp/resources/js/components/AnalysesQueue.jsx
Fixes a layout issue on my displays where the number get pushed outside the blue queue box.
N/A
=> Cleaned up styles on AnalysesQueue.jsx on smaller displays

CHANGELOG.md, pom.xml, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysisController.java, src/main/webapp/pages/analysis/details/details.html, src/main/webapp/pages/pipelines/types/generic_pipeline.html
Fixed a GUI bug that was not properly showing single end files when selecting inputs for analysis pipeline.  Also added displaying those files in the analysis results.  All the back end stuff worked with it with no changes.
In the future I'd like to beef up the cart to separate the single-end and paired-end pipelines and maybe only show the tools applicable to the data in the cart.  For now this is a start.
**Note this is a hotfix and must be merged into both master and development.**
Fixes #53 
=> Hotfix single end analyises

src/main/webapp/resources/js/components/Header/Breadcrumbs.jsx, src/main/webapp/resources/js/components/icons/Icons.jsx, src/main/webapp/resources/js/components/popovers/HelpPopover.jsx, src/main/webapp/resources/js/components/session/SessionModal.jsx, src/main/webapp/resources/js/pages/cart/components/CartToolsMenu.jsx, src/main/webapp/resources/js/pages/cart/components/SampleRenderer.jsx, src/main/webapp/resources/js/pages/projects/linelist/components/Table/renderers/DateCellRenderer.jsx, src/main/webapp/resources/js/pages/projects/linelist/components/TableControlPanel/TableControlPanel.jsx, src/main/webapp/resources/js/pages/projects/list/ProjectsTable.jsx
Cleans up some missed icons from the last merge request.
N/A
=> Icons cleanup

CHANGELOG.md, src/main/webapp/package.json, src/main/webapp/yarn.lock
Removed git hook for prettier as it was causing problems.
N/A
=> Remove husky git hook runner

src/main/webapp/resources/js/apis/analysis/analysis.js, src/main/webapp/resources/js/apis/linker/linker.js, src/main/webapp/resources/js/components/AnalysesTable/AnalysesTable.jsx, src/main/webapp/resources/js/components/PhylocanvasComponent.jsx, src/main/webapp/resources/js/pages/analysis/components/AnalysisPhylogeneticTree.jsx, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/analysis/AnalysisDetailsPage.java
Updated phylocanvascomponent to a functional react component. Updated js/apis/* code to use setBaseUrl.
=> Analysis/ phylocanvas react functional component

CHANGELOG.md, src/main/webapp/resources/js/pages/sequence-files/run-files.js, src/main/webapp/resources/js/pages/sequencing-runs/SequencingRunsList.jsx
This is another small table that did not need DataTables.
#413 
=> Remove DataTables from sequencing run files page

src/main/java/ca/corefacility/bioinformatics/irida/config/security/IridaWebSecurityConfig.java, src/main/java/ca/corefacility/bioinformatics/irida/config/web/IridaUIWebConfig.java
Added a `/static` endpoint on the webserver which serves files from `/etc/irida/static` for help with customizing the login page.
To be added to #639 
=> /static endpoint for customizing brand

doc/developer/setup/index.md, src/main/webapp/package.json, src/main/webapp/pages/password/reset_created.html, src/main/webapp/webpack.config.js, src/main/webapp/yarn.lock
This PR remove the last remnant of bower from the UI layer.  The password_created page was the last page that had a reference to bower and that has now been updated.
Fixes #125 
=> Final bower removal

doc/administrator/web/ubuntu/index.md, doc/developer/getting-started/index.md, doc/developer/setup/index.md
Removing all notes of Java 8 from the docs.  Didn't add to changelog since it should have been done already.
Related to #473 
=> removed all notes of java 8 from the docs

src/main/java/ca/corefacility/bioinformatics/irida/model/sequenceFile/Fast5Object.java, src/main/java/ca/corefacility/bioinformatics/irida/web/controller/api/projects/RESTProjectSamplesController.java, src/main/java/ca/corefacility/bioinformatics/irida/web/controller/api/samples/RESTSampleSequenceFilesController.java, src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/20.05/all-changes.xml, src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/20.05/fast5-file-model.xml, src/test/java/ca/corefacility/bioinformatics/irida/web/controller/test/unit/project/RESTProjectSamplesControllerTest.java
Added model classes and liquibase changes for .fast5 files
Related to #117 
=> Model and db changes for fast5

src/main/resources/i18n/messages.properties
Added back missing key for `users.id`
N/A
=> Add missing messages key for users.id

CHANGELOG.md, doc/developer/getting-started/index.md
Updated the Getting Started docs to include the username and password necessary to log in to IRIDA with a newly created development database, and changed the install-libs.sh run command, as `bash install-libs.sh` was outdated.
N/A
=> Dev primer updates

doc/developer/getting-started/index.md
Updated Spring docs link to our current version.  In this case it was really necessary since we moved up a major version.
Fixes #600 
=> updated spring version in getting started docs

README.md
Added a link to the pipeline plugin list repo in the README.md
N/A
~* [x] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.~
=> Added pipeline plugin link to the readme

src/main/webapp/pages/login.html, src/main/webapp/resources/js/pages/LoginPage.jsx
Fixed issue where login logo was not displayed when context path was changed.  This was cause by the wrong name on a variable on the login.html page.
N/A
=> Login logo fix

CHANGELOG.md, src/main/webapp/resources/js/pages/visualizations/phylogenetics/components/app/app.module.js
Added 'angular.ui.bootstrap' to the list of requires for the angular module which was preventing the advanced visualization view from loading.
=> Advanced visualization view fix

src/main/webapp/resources/js/components/Header/PageHeader.jsx, src/main/webapp/resources/js/pages/SamplePage.jsx, src/main/webapp/resources/js/pages/UserGroupsPage/components/UserGroupDetailsPage.jsx, src/main/webapp/resources/js/pages/UserGroupsPage/components/UserGroupsTable.jsx, src/main/webapp/resources/js/pages/UserGroupsPage/index.js
Fixes:
1. Sample file buttons not displaying
1. Groups page not displaying at all.
N/A
=> Fixes for sample buttons and groups page.

CHANGELOG.md, src/main/webapp/resources/js/pages/analysis/components/Analysis.jsx, src/main/webapp/resources/js/pages/analysis/components/AnalysisError.jsx, src/main/webapp/resources/js/pages/analysis/components/AnalysisOutputFiles.jsx, src/main/webapp/resources/js/pages/analysis/components/AnalysisSettings.jsx, src/main/webapp/resources/js/pages/analysis/components/AnalysisSistr.jsx, src/main/webapp/resources/js/pages/analysis/index.js
Updated analysis results page urls to work with a context path.
=> Analysis context path

src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysisAjaxController.java, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/dto/AnalysisJobError.java, src/main/resources/i18n/messages.properties, src/main/webapp/resources/js/pages/analysis/components/AnalysisError.jsx, src/main/webapp/resources/js/pages/analysis/components/jobErrors/GalaxyJobInfo.jsx, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/analysis/AnalysisDetailsPageIT.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/analysis/AnalysisDetailsPage.java, src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysisAdminView.xml
Added a link to the galaxy history id for the admin if a galaxy job error object is not returned.
Fixes #440 
=> Analysis error page galaxy history id link

CHANGELOG.md, src/main/webapp/resources/js/pages/analysis/components/AnalysisPhylogeneticTree.jsx, src/main/webapp/resources/js/pages/analysis/components/outputs/OutputFilePreview.jsx
Changed width of outputs to span the page width.
=> Outputs width change

src/main/webapp/resources/sass/pages/sample-files.scss
Fixes issue where file upload was displayed in a very incorrect fashion on the pipeline launch page.
N/A
=> Fix file upload styles

src/main/java/ca/corefacility/bioinformatics/irida/ria/web/admin/AdminBaseController.java, src/main/resources/i18n/messages.properties, src/main/webapp/pages/admin/index.html, src/main/webapp/pages/template/main-navigation.html, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/admin/AdminPageIT.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/admin/AdminPage.java, src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/admin/AdminPageView.xml
Added button to navbar (only visible to admins) that links to the base admin panel.
N/A
=> Added navbar button for base admin panel

CHANGELOG.md, pom.xml, src/main/webapp/pages/projects/project_samples_metadata_template.html, src/main/webapp/resources/js/pages/projects/metadata-template/create-metadata-template.js
What did you change in this pull request? Provide a description of files changed, user interactions changed, etc. Include how to test your changes.
*   ~Tests added (or description of how to test) for any new features.~
*   ~User documentation updated for UI or technical changes.~
=> Hotfix: new metadata template select2 fix

CHANGELOG.md, src/main/webapp/package.json, src/main/webapp/yarn.lock
Updated chromedriver to version 83 as travis was giving errors with 79.
N/A
=> Chromedriver 83 update

CHANGELOG.md, src/main/webapp/package.json, src/main/webapp/resources/js/pages/UserGroupsPage/components/UserGroupDetailsPage.jsx, src/main/webapp/yarn.lock, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/groups/UserGroupsDetailsPage.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/AssociatedProjectPage.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectSamplesPage.java
Updated to latest release of Ant Design.  Affected several tests which have been fixed in this PR.
N/A
*   [ ] ~~Tests added (or description of how to test) for any new features.~~
*   [ ] ~~User documentation updated for UI or technical changes.~~
=> Upgrade ant design v4.4.2

CHANGELOG.md, src/main/webapp/yarn.lock
Updated yarn.lock file which was causing a dependabot alert for a security vulnerabilty (elliptic < 6.5.3).
=> Update yarn lock file to fix security vulnerability alert

src/main/java/ca/corefacility/bioinformatics/irida/ria/web/UserGroupsController.java, src/main/webapp/pages/admin/index.html, src/main/webapp/resources/js/contexts/UserGroupsContext.js, src/main/webapp/resources/js/pages/UserGroupsPage/components/CreateNewUserGroupButton.jsx, src/main/webapp/resources/js/pages/UserGroupsPage/components/UserGroupDetailsPage.jsx, src/main/webapp/resources/js/pages/UserGroupsPage/components/UserGroupMembersTable.jsx, src/main/webapp/resources/js/pages/UserGroupsPage/components/UserGroupsPage.jsx, src/main/webapp/resources/js/pages/UserGroupsPage/components/UserGroupsTable.jsx, src/main/webapp/resources/js/pages/UserGroupsPage/index.js, src/main/webapp/resources/js/pages/admin/components/Admin.jsx, src/main/webapp/resources/js/pages/admin/components/AdminSideMenu.jsx, src/main/webapp/resources/js/pages/admin/components/AdminUserGroupsPage.jsx, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/groups/UserGroupsIT.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/groups/UserGroupsDetailsPage.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/groups/UserGroupsListingPage.java
Created AdminUserGroupsPage that imports in the user groups components to be used in the admin panel and provides them with the correct admin panel routing so redirects work as intended. To test ensure that the redirects work correctly within the admin panel and outside as well.
N/A
=> Fixed user groups redirect routing

src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectSamplesPage.java
Increased waitForTime to 300 from 100 as the test to add a new sample kept failing due to not enough of a wait.
=> Project add new sample test timing

CHANGELOG.md, pom.xml, src/main/webapp/resources/js/components/project-members/ProjectMembersTable.jsx, src/main/webapp/resources/js/pages/projects/linelist/components/Toolbar/Toolbar.jsx, src/main/webapp/resources/js/pages/projects/linelist/components/Tour/steps.js, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/ProjectMembersPage.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectLineListPage.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectLineListPageIT.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectMembersPageIT.java
~~- [ ] Add Group to project button displayed~~ (will do in dev branch)
~~- [ ] Settings metadata template~~ (does not seem to be an issue.)
This was re-pushed from #771 which got messed up
N/A
~~ * [ ] User documentation updated for UI or technical changes. ~~
=> Hotfix collaborator buttons

src/main/webapp/resources/js/components/icons/Error.jsx, src/main/webapp/resources/js/components/icons/Icons.jsx, src/main/webapp/resources/js/components/icons/Success.jsx, src/main/webapp/resources/js/pages/analysis/components/Analysis.jsx, src/main/webapp/yarn.lock
Updated icons next to analysis name on the analysis details page to use the ant design icons.
=> Updated icons next to analysis name on the analysis details page

doc/user/user/pipelines/index.md, src/main/webapp/resources/js/contexts/AnalysisContext.js, src/main/webapp/resources/js/pages/analysis/components/AnalysisSteps.jsx
Updated AnalysisSteps to include states (prepared, finished_running, transferring, post_processing). Changed delay for polling of analysis state and duration to a minute.
~* [ ] User documentation updated for UI or technical …
=> AnalysisSteps state update

src/main/webapp/resources/js/apis/clients/clients.js, src/main/webapp/resources/js/pages/admin/components/clients/add/AddClientModal.jsx
Instead of just updating the clients listing table, the user is now redirect to the client details page.
N/A
=> Redirect to client details page after creation.

UPGRADING.md
Added information about the database changes to the upgrading guide.
N/A
=> adding db change notice to upgrading guide

doc/_includes/administrator/galaxy/setup/automated-tool-install.md, doc/administrator/galaxy/existing-galaxy/index.md, doc/administrator/galaxy/index.md, doc/administrator/galaxy/pipelines/assembly-annotation-collection/index.md, doc/administrator/galaxy/pipelines/assembly-annotation/index.md, doc/administrator/galaxy/pipelines/phylogenomics/index.md, doc/administrator/galaxy/pipelines/refseq_masher/index.md, doc/administrator/galaxy/pipelines/sistr/index.md, doc/administrator/galaxy/pipelines/test/snvphyl/snvphyl_workflow.ga, doc/administrator/galaxy/setup/index.md, doc/developer/tools/pipelines/index.md
1. I fixed up the SNVPhyl install documentation to point to the correct tool.
2. I removed all mentions in our documentation of the IRIDA Toolshed.
3. I removed a few mentions in the documentation about `tbl2asn` updates (since they no longer apply with latest assembly pipeline).
4. I fixed a few broken links.
Note this is a PR to `master` and so will have to be merged into both `master` and `development`.
None.
* ~[ ] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.~
=> Doc fixes for SNVPhyl and removing mention of IRIDA Toolshed

CHANGELOG.md, pom.xml, src/main/resources/i18n/messages.properties, src/main/webapp/entries.js, src/main/webapp/pages/sequencingRuns/_details_base.html, src/main/webapp/pages/sequencingRuns/details.html, src/main/webapp/resources/js/apis/sequencing-runs/sequencing-runs.js, src/main/webapp/resources/js/pages/sequencing-runs/details/index.js, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/sequencingRuns/SequencingRunDetailsPage.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/sequencingRuns/SequencingRunDetailsPageIT.java
Fixed issue where sequencing runs could not be deleted on the details page.  Refactored page header into a react component to remove angular from the page.
Fixes #808 
*   [x] Tests added (or description of how to test) for any new features.
=> HOTFIX: Fixed removal of sequencing runs

CHANGELOG.md, src/main/webapp/package.json, src/main/webapp/yarn.lock
This is another old package that we no longer use.
N/A
=> Remove bootstap sass

CHANGELOG.md, src/main/webapp/resources/js/components/ant.design/table-renderers.js
Fixes an issue where, after a new user is created and not logged in, their last login date in the users table shows up as Dec 31, 1969.
Fixes #838 
=> Fixed last login bug

src/main/java/ca/corefacility/bioinformatics/irida/model/announcements/Announcement.java, src/main/resources/ca/corefacility/bioinformatics/irida/database/all-changes.xml, src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/21.01/all-changes.xml, src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/21.01/announcements_upgrade.xml, src/main/resources/ca/corefacility/bioinformatics/irida/sql/required-data.sql, src/main/resources/scripts/announcements/README.txt, src/main/resources/scripts/announcements/generate_json.py, src/main/resources/scripts/announcements/requirements.txt, src/main/resources/scripts/announcements/update_announcements.py
- Updated the announcements to include a title and priority
- Created a script to parse the title from message and populate the new column
=> Announcements upgrade database

src/main/java/ca/corefacility/bioinformatics/irida/model/announcements/Announcement.java, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/announcements/AnnouncementsController.java, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/announcements/dto/AnnouncementRequest.java, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIAnnouncementsService.java, src/test/java/ca/corefacility/bioinformatics/irida/service/impl/integration/AnnouncementServiceImplIT.java, src/test/java/ca/corefacility/bioinformatics/irida/web/controller/test/unit/announcements/AnnouncementsAjaxControllerTest.java, src/test/java/ca/corefacility/bioinformatics/irida/web/controller/test/unit/announcements/AnnouncementsControllerTest.java, src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/announcements/AnnouncementPageIT.xml, src/test/resources/ca/corefacility/bioinformatics/irida/service/impl/AnnouncementServiceImplIT.xml
Changes to announcements request, controller and service
=> Announcements upgrade backend

src/main/webapp/package.json, src/main/webapp/yarn.lock
Updated package.json file to specify chromedriver version as setting the latest was not working.
=> Set chromedriver to version 87.0.0 as latest not working

src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/ReferenceFileAjaxController.java, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/settings/ProjectReferenceFileController.java, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIProjectReferenceFileService.java, src/main/webapp/resources/js/apis/projects/reference-files.js, src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/files/ReferenceFileAjaxControllerTest.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/services/UIProjectReferenceFileServiceTest.java
Moved getting of reference files for projects into the reference fil ajax controller.
=> Moved project reference file request

src/main/java/ca/corefacility/bioinformatics/irida/config/repository/IridaApiFilesystemRepositoryConfig.java
Updated directory check at startup not to crash if using cloud storage.
=> Object_store/_update-filesystem-startup

src/main/webapp/pages/oauth/access_confirmation.html, src/main/webapp/resources/js/apis/oauth/oauth.js
Fixes issue with sending files to Galaxy. Pop up connection window would close before the galaxy auth code was sent.
N/A
=> Fix for oauth redirect

CHANGELOG.md, src/main/webapp/package.json, src/main/webapp/yarn.lock
Update jest to fix node-notifier warning
Fixes issue dependabot warned about for node-notifier
=> Updated jest to fix node-notifier warning

CHANGELOG.md, pom.xml, src/main/webapp/resources/js/pages/projects/samples/project-samples.js
Fixed issue with samples table not displaying created and modified date for samples. The issue arose from us trying to destructure a parameter which wasn't an object when trying to format the dates.
=> HOTFIX: Fix project sample table dates

src/main/webapp/resources/js/components/Header/MainNavigation.jsx
Administrators should not have the "cog" icon displayed on the main navigation since all this is available to them in there menus
N/A
=> Hide cog icon if user is an administrator

src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/pipeline/DynamicSource.java, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/launchPipeline/dtos/UIPipelineDetailsResponse.java, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIPipelineService.java, src/main/resources/i18n/messages.properties, src/main/webapp/resources/js/pages/launch/DynamicSources.jsx, src/main/webapp/resources/js/pages/launch/LaunchContent.jsx, src/main/webapp/resources/js/pages/launch/LaunchFiles.jsx, src/main/webapp/resources/js/pages/launch/LaunchForm.jsx, src/main/webapp/resources/js/pages/launch/LaunchPage.jsx, src/main/webapp/resources/js/pages/launch/LaunchParameters.jsx, src/main/webapp/resources/js/pages/launch/ParameterWithOptions.jsx, src/main/webapp/resources/js/pages/launch/files/SampleFilesListItem.jsx, src/main/webapp/resources/js/pages/launch/launch-context.js, src/main/webapp/resources/js/pages/launch/parameters/SavedParameters.jsx, src/main/webapp/yarn.lock, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectRemoteSettingsIT.java
Display dynamic pipeline parameters for pipelines that require them (e.g. MentaList).  These are parameters that are pull from Galaxy (e.g. which database to use).
Related to #777 
=> Pipeline Launch: dynamic parameters

src/main/webapp/resources/js/components/Header/main-navigation/components/CartLink.jsx
Moved the cart icon link outwards so users can click anywhere on the highlighted cart button area.  Previously you had to click on the icon which was inconsistent with the other top bar icons.
N/A
Doesn't actually change any function, just a tiny usage thing.
=> Made cart link easier to click

CHANGELOG.md, pom.xml
Upgraded maven package to run `yarn` during the build process. 
N/A
=> Updated frontend-maven-plugin

CHANGELOG.md, UPGRADING.md, src/main/webapp/package.json, src/main/webapp/yarn.lock
Updated the links in the UPGRADING.md file to the new docs site
Related to #798
=> Changed links to new docs in UPGRADING

src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIPipelineService.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pipelines/AssemblyPipelinePageIT.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/services/UIPipelineServiceTest.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/services/UIPipelineStartServiceTest.java
Added testing for UI pipeline services.
N/A
=> Launch service testing

CHANGELOG.md, src/main/webapp/package.json, src/main/webapp/resources/js/components/Header/main-navigation/components/CartLink.jsx, src/main/webapp/resources/js/pages/analysis/components/AnalysisTabularPreview.jsx, src/main/webapp/resources/js/pages/projects/reference-files/ReferenceFiles.jsx, src/main/webapp/yarn.lock
Updated to latest release of Ant Design.
N/A
=> Ant Design update v4.12.3

CHANGELOG.md, src/main/webapp/resources/js/pages/analyses/analysis-outputs-table.js
Added the missing filter menus to the analysis outputs table. Added a specific date filter to the date column
Fixes #899 
=> Fixed missing filter menus on analysis outputs table

src/main/webapp/resources/js/components/Header/MainNavigation.jsx, src/main/webapp/resources/js/components/Header/main-navigation/components/AnnouncementsSubMenu.jsx, src/main/webapp/resources/js/components/Header/main-navigation/style.css
Fixes strange issue with styled-components on the linelist page.
N/A
=> Fixes layout issue with announcement icon

src/main/java/ca/corefacility/bioinformatics/irida/model/sample/metadata/MetadataRestriction.java, src/main/java/ca/corefacility/bioinformatics/irida/repositories/sample/MetadataRestrictionRepository.java, src/main/java/ca/corefacility/bioinformatics/irida/service/impl/sample/MetadataTemplateServiceImpl.java, src/main/java/ca/corefacility/bioinformatics/irida/service/sample/MetadataTemplateService.java, src/main/resources/ca/corefacility/bioinformatics/irida/database/all-changes.xml, src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/21.05/all-changes.xml, src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/21.05/metadata-restrictions.xml
Added the `MetadataRestriction` class which will be used to define restrictions on who can view a metadata column
Related to #931 
=> Metadata field restriction

src/main/webapp/resources/js/components/form/InputWithOptions.jsx, src/main/webapp/resources/js/pages/launch/LaunchForm.jsx, src/main/webapp/resources/js/pages/launch/launch-context.js, src/main/webapp/resources/js/utilities/form-utilities.js
Fixed Snvphyl pipeline crashing if enable density filter was not selected.
=> Enable snv density filter fix

CHANGELOG.md, src/main/webapp/package.json, src/main/webapp/yarn.lock
Update chromedriver version to 90
N/A
=> Updated chromedriver to 90

src/main/webapp/entries.js, src/main/webapp/pages/projects/settings/_base.html, src/main/webapp/resources/js/apis/projects/projects.js, src/main/webapp/resources/js/pages/projects/reference-files/index.js, src/main/webapp/resources/js/pages/projects/settings/components/ReferenceFiles.jsx, src/main/webapp/resources/js/pages/projects/settings/components/SettingsNav.jsx, src/main/webapp/resources/js/pages/projects/settings/index.js
=> Project settings references

CHANGELOG.md, src/main/webapp/package.json, src/main/webapp/yarn.lock
Updated lodash to fix security vulnerability in version \<4.17.21.  For more information you can read https://snyk.io/vuln/SNYK-JS-LODASH-1018905
N/A
=> Updated lodash to fix security vulnerability

src/main/webapp/resources/js/pages/projects/settings/components/SettingsNav.jsx, src/main/webapp/resources/js/pages/projects/settings/index.js
Fixes issue where collaborators could see delete project in the new project settings page.
N/A
=> Fixed issue where collaborators could see delete project

src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIPipelineStartService.java
Keep samples after pipeline launch
N/A
=> Don't empty the cart on pipeline lauch

src/main/webapp/package.json, src/main/webapp/yarn.lock
Fixes dependabot warning for browserslist
~*   [ ] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.~
~*   [ ] Tests added (or description of how to test) for any new features.~
~*   [ ] User documentation updated for UI or technical changes.~
=> Use browserslist @ 4.16.6

CHANGELOG.md, doc/administrator/web/config/irida.conf, doc/administrator/web/index.md, src/main/java/ca/corefacility/bioinformatics/irida/config/services/IridaPluginConfig.java, src/main/resources/ca/corefacility/bioinformatics/irida/config/filesystem.properties
Make the pipeline plugin path configurable via `pipeline.plugin.path` config option.
None
=> Make plugin path configurable

CHANGELOG.md, src/main/webapp/package.json, src/main/webapp/yarn.lock
Moved off alpha release to stable version of redux toolkit
N/A
* ~~[ ] Tests added (or description of how to test) for any new features.~~
* ~~[ ] User documentation updated for UI or technical changes.~~
=> Update Redux Toolkit to stable version

src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/ProjectAnalysesAjaxController.java, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIProjectAnalysesService.java, src/main/webapp/resources/js/apis/projects/analyses.js, src/main/webapp/resources/js/pages/projects/project-analyses/components/AutomatedSingleSampleAnalysisOutputs.jsx, src/main/webapp/resources/js/pages/projects/project-analyses/components/ProjectAnalysesPage.jsx
Updated project analyses automated single sample analysis outputs to use Ant Design.
=> Project analyses/ automated outputs

CHANGELOG.md, pom.xml, src/main/java/ca/corefacility/bioinformatics/irida/service/impl/AnalysisExecutionScheduledTaskImpl.java, src/test/java/ca/corefacility/bioinformatics/irida/service/impl/unit/AnalysisExecutionScheduledTaskImplTest.java
Fixed a boolean logic oops that was spamming email for anyone who selected to get an email on pipeline completion.
Fixes #1059 
=> Hotfix: Fixing analysis email spam

CHANGELOG.md, src/main/webapp/package.json, src/main/webapp/yarn.lock
Updated chromedriver to version 92.0.0
N/A
=> Chromedriver update to v92

src/main/webapp/resources/js/pages/projects/settings/components/metadata/MetadataFieldsListManager.jsx
Fix issue when updating a metadata field restriction as a manager through the UI the UI does not properly update.
N/A
* ~~ [ ] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.~~
* ~~ [ ] Tests added (or description of how to test) for any new features.~~
* ~~[ ] User documentation updated for UI or technical changes.~~
=> Fix issue updating UI for metadata filed restrictions

src/main/java/ca/corefacility/bioinformatics/irida/model/workflow/analysis/ProjectSampleAnalysisOutputInfo.java, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/ProjectAnalysesAjaxController.java, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIProjectAnalysesService.java, src/main/webapp/resources/js/apis/projects/analyses.js, src/main/webapp/resources/js/pages/projects/project-analyses/components/SingleSampleAnalysisOutputs.jsx
=> Project analyses/ file downloads

src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/services/UIAnalysesOutputsServiceTest.java
Test was requesting the security context which had not been mocked.
=> Fixed broken UIAnalysesOutputsServiceTest

CHANGELOG.md, src/main/webapp/package.json, src/main/webapp/yarn.lock
Fixes dependabot issue with path-parse.
N/A
=> Fixes issue of path-parse

CHANGELOG.md, src/main/webapp/package.json, src/main/webapp/yarn.lock
Updated to newer chromedriver v93.0.1
N/A
=> Updated chromedriver to v93.0.1

UPGRADING.md
Added info to upgrading guide for 21.09.
N/A
=> Added 21.09 info to upgrading guide

doc/_includes/tutorials/common/initial-data.md, doc/administrator/galaxy/existing-galaxy/index.md, doc/administrator/web/index.md, doc/developer/index.md, doc/downloads/index.md, doc/user/administrator/troubleshooting/pipelines/index.md, doc/user/tutorials/assembly/index.md, doc/user/tutorials/mentalist/index.md, doc/user/tutorials/sistr/index.md
Update documentation to reflect new location of public datasets and virtualbox
=> update to latest locations for download

CHANGELOG.md, src/main/webapp/package.json, src/main/webapp/resources/js/components/Header/main-navigation/components/AnnouncementsSubMenu.jsx, src/main/webapp/resources/js/components/Header/main-navigation/style.css, src/main/webapp/yarn.lock, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/components/Announcements.java
Upgrading ant design to latest stable version & fixing issues associated with the upgrade.
#1116
=> Update ant design to v4.16.13

src/main/java/ca/corefacility/bioinformatics/irida/ria/web/samples/SamplesAjaxController.java, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/samples/dto/UpdateSampleAttributeRequest.java, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UISampleService.java, src/main/resources/i18n/messages.properties, src/main/webapp/resources/js/apis/samples/samples.js, src/main/webapp/resources/js/components/samples/SampleDetailViewer.jsx, src/main/webapp/resources/js/components/samples/components/SampleDetails.jsx, src/main/webapp/resources/js/components/samples/components/SampleInfo.jsx, src/main/webapp/resources/js/components/samples/sampleSlice.js, src/main/webapp/resources/js/components/samples/store.js, src/main/webapp/yarn.lock, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/components/SampleDetailsViewer.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectSamplesPage.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectSamplesPageIT.java
Connected SampleDetailViewer -> details tab to server. Added functionality to edit sample details fields. This is a new PR with the same changes as #1129 which got corrupted on local machine.
~* [ ] User documentation updated for UI …
=> Sample details refactor/ details tab

CHANGELOG.md, doc/_includes/tutorials/common/samples/copy-samples.md, src/main/resources/i18n/messages.properties, src/main/webapp/resources/js/pages/projects/linelist/components/ShareSampleButton/index.jsx, src/main/webapp/resources/js/pages/projects/linelist/components/Toolbar/Toolbar.jsx, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectLineListPage.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectLineListPageIT.java
Added the ability to share samples from the project line list page.
N/A
*   [x] Tests added (or description of how to test) for any new features.
*   [x] User documentation updated for UI or technical changes.
=> Share samples from linelist page

src/main/webapp/pages/analyses/user-analysis-outputs.html
Fixed css issue with user analyses outputs page caused by incorrect entry for page css.
=> User analyses outputs css fix

CHANGELOG.md, src/main/webapp/resources/js/components/form/InputWithOptions.jsx, src/main/webapp/resources/js/utilities/form-utilities.js
Launch Page crashes if pipeline has dynamic parameters with only one option.  FIxed by adding a check and added a single disabled text input with the value.
N/A
=> Address single dynamic parameter in pipeline launch

src/main/webapp/resources/js/apis/projects/user-groups.js, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/analysis/AnalysisDetailsPage.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/NcbiExportPage.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectMetadataPage.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectMetadataIT.java
Fixed flaky ui tests caused by timing issues.
=> Fix flaky ui tests

pom.xml
Removed @tom114 from an active developer, and added @ericenns.  Updated email addresses for all.
N/A
=> Updated pom file to reflect developers and update emails

src/main/java/ca/corefacility/bioinformatics/irida/config/environment/IridaEnvironmentPostProcessor.java, src/main/resources/META-INF/spring.factories, src/main/resources/ca/corefacility/bioinformatics/irida/config/jdbc.dev.properties, src/main/resources/ca/corefacility/bioinformatics/irida/config/jdbc.it.properties, src/main/resources/ca/corefacility/bioinformatics/irida/config/jdbc.prod.properties
Add in custom Spring Boot EnvironmentPostProcessor to translate deprecated properties into valid properties.
=> Spring boot translate deprecated properties

.github/workflows/ci-test.yml, CHANGELOG.md, doc/developer/interface/testing/index.md, run-tests.sh, src/main/webapp/chromedriver, src/main/webapp/package.json, src/main/webapp/yarn.lock
Fix UI Tests that are failing due to chromedriver version incompatibilities by using chromedriver provided by the image. This should fix this permanently.
=> Update github actions to use chromedriver provided by ubuntu-20.04 image

src/main/webapp/resources/js/components/project/ProjectNav.jsx, src/main/webapp/resources/js/pages/projects/settings/components/AssociatedProjects.jsx, src/main/webapp/resources/js/pages/projects/settings/components/DeleteProject.jsx, src/main/webapp/resources/js/pages/projects/settings/components/ProjectDetails.jsx, src/main/webapp/resources/js/pages/projects/settings/components/ProjectMembers.jsx, src/main/webapp/resources/js/pages/projects/settings/components/ProjectProcessing.jsx, src/main/webapp/resources/js/pages/projects/settings/components/ProjectSynchronizationSettings.jsx, src/main/webapp/resources/js/pages/projects/settings/components/ProjectUserGroups.jsx, src/main/webapp/resources/js/pages/projects/settings/components/ReferenceFiles.jsx, src/main/webapp/resources/js/pages/projects/settings/components/SettingsNav.jsx, src/main/webapp/resources/js/pages/projects/settings/components/metadata/MetadataFields.jsx, src/main/webapp/resources/js/pages/projects/settings/components/metadata/MetadataLayout.jsx, src/main/webapp/resources/js/pages/projects/settings/components/metadata/MetadataTemplate.jsx, src/main/webapp/resources/js/pages/projects/settings/components/metadata/MetadataTemplateCreate.jsx, src/main/webapp/resources/js/pages/projects/settings/components/metadata/MetadataTemplateManager.jsx, src/main/webapp/resources/js/pages/projects/settings/components/metadata/MetadataTemplateMember.jsx, src/main/webapp/resources/js/pages/projects/settings/components/metadata/MetadataTemplates.jsx, src/main/webapp/resources/js/pages/projects/settings/index.js, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/AssociatedProjectPage.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectDetailsPage.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectMetadataPage.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/remoteapi/RemoteAPIDetailsPage.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/CreateProjectIT.java
Removed `@reach/router` and replace with react router
N/A
=> React router project settings

src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/UpdatedAnalysisProgress.java, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysisAjaxController.java, src/main/webapp/resources/js/contexts/AnalysisContext.js, src/main/webapp/resources/js/pages/analysis/AnalysisCompletePage.jsx, src/main/webapp/resources/js/pages/analysis/AnalysisErrorPage.jsx, src/main/webapp/resources/js/pages/analysis/AnalysisRunningPage.jsx, src/main/webapp/resources/js/pages/analysis/components/AnalysisError.jsx, src/main/webapp/resources/js/pages/analysis/components/AnalysisMenu.jsx, src/main/webapp/resources/js/pages/analysis/components/AnalysisSettings.jsx, src/main/webapp/resources/js/pages/analysis/components/AnalysisSistr.jsx, src/main/webapp/resources/js/pages/analysis/components/settings/AnalysisDetails.jsx, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/analysis/AnalysisDetailsPageIT.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/analysis/AnalysisDetailsPage.java
Fixed tree output view for analyses when updated via polling (tree would not display when analysis state changed from running to completed). Updated analysis results page tests to work with react router. Fixed menu item highlighting on analysis -> settings submenu
~* [ ] Tests added (or description of how …
=> Analysis tree output fix

src/main/webapp/resources/js/pages/cart/components/CartTools.jsx, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/cart/CartPage.java
Updated cart page to use `react-router`
N/A
N/A
=> React router cart tools

CHANGELOG.md, src/main/webapp/package.json, src/main/webapp/resources/js/pages/projects/project-analyses/components/AnalysesNav.jsx, src/main/webapp/resources/js/pages/projects/project-analyses/components/AutomatedSingleSampleAnalysisOutputs.jsx, src/main/webapp/resources/js/pages/projects/project-analyses/components/ProjectAnalysesPage.jsx, src/main/webapp/resources/js/pages/projects/project-analyses/components/SharedSingleSampleAnalysisOutputs.jsx, src/main/webapp/resources/js/pages/projects/project-analyses/index.js, src/main/webapp/yarn.lock
Updated to `react-router` on the project analysis page.  THis is the last one so removed dependency and updated CHANGELOG
=> React router project analyses

CHANGELOG.md, doc/developer/setup/index.md, run.sh
Added ability to add `--no-yarn` to ignore the yarn build
=> Updated run script to ignore yarn

src/main/java/ca/corefacility/bioinformatics/irida/ria/web/samples/SamplesAjaxController.java, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UISampleService.java, src/main/resources/i18n/messages.properties, src/main/webapp/resources/js/apis/samples/samples.js, src/main/webapp/resources/js/components/samples/components/SampleFileContenate.jsx, src/main/webapp/resources/js/components/samples/components/SampleFileList.jsx, src/main/webapp/resources/js/components/samples/components/SampleFiles.jsx, src/main/webapp/resources/js/components/samples/components/SampleMetadata.jsx, src/main/webapp/resources/js/components/samples/sampleFilesSlice.js, src/main/webapp/resources/js/components/sequence-files/PairedFileRenderer.jsx, src/main/webapp/resources/js/components/sequence-files/SequenceFileDetailsRenderer.jsx, src/main/webapp/resources/js/components/sequence-files/SequenceFileHeader.jsx, src/main/webapp/resources/js/components/sequence-files/SequenceFileHeaderOwner.jsx, src/main/webapp/resources/js/components/sequence-files/SingleEndFileRenderer.jsx, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/AbstractIridaUIITChromeDriver.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/CartPageIT.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/components/SampleDetailsViewer.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/cart/CartPage.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/samples/SamplesAjaxControllerTest.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/services/UISampleServiceTest.java, src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/CartView.xml
Added functionality to concatenate sample files.
=> Sample details refactor/ file concat

CHANGELOG.md, pom.xml, src/main/java/ca/corefacility/bioinformatics/irida/config/web/OpenAPIConfig.java, src/main/java/ca/corefacility/bioinformatics/irida/model/MutableIridaThing.java, src/main/java/ca/corefacility/bioinformatics/irida/model/Timestamped.java, src/main/java/ca/corefacility/bioinformatics/irida/model/joins/Join.java, src/main/java/ca/corefacility/bioinformatics/irida/model/sample/Sample.java, src/main/resources/application.properties
Added schema annotation to specify Long.class returned for createdDate and modifiedDate attributes.
Fixes #1186
=> Hotfix: Swagger format date fix

CHANGELOG.md, pom.xml, src/main/java/ca/corefacility/bioinformatics/irida/model/IridaRepresentationModel.java, src/test/java/ca/corefacility/bioinformatics/irida/repositories/remote/impl/ProjectRemoteRepositoryImplTest.java
Fixed issue with syncing remote projects from version 20.09 and older.
Fixes #1206 
=> hotfix: Fixed syncing remote projects from version 20.09 and older.

doc/developer/files/eclipse-code-formatter.xml, doc/developer/files/intellij-code-style-schemes.xml, src/main/java/ca/corefacility/bioinformatics/irida/model/user/User.java, src/main/java/ca/corefacility/bioinformatics/irida/pipeline/results/updater/impl/BioHanselSampleUpdater.java
Update Eclipse and Intellij code formatting to be consistent.
=> Updated code formatting to be consistent between intellij and eclipse.

CHANGELOG.md, src/main/webapp/resources/js/pages/projects/settings/components/ProjectDetails.jsx
Project details could not update because the project identifier was not set currently after I updated the react router.  
N/A
=> HOTFIX: Fixed issue with updating project details

.github/workflows/ci-test.yml
Updated CI JavaScript heap size
=> Updated CI JavaScript heap size

src/main/java/ca/corefacility/bioinformatics/irida/repositories/ProjectRepository.java, src/main/webapp/package.json, src/main/webapp/resources/js/components/Header/main-navigation/components/GlobalSearch.jsx, src/main/webapp/resources/js/pages/projects/linelist/components/ShareSampleButton/index.jsx, src/main/webapp/resources/js/pages/projects/share/ShareLarge.jsx, src/main/webapp/resources/js/pages/projects/share/index.js, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/analysis/AnalysesUserOutputsPage.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/analysis/AnalysesUserPage.java
If sharing a large number of samples, a progress bar will be displayed to ensure the user know the status.
N/A
=> Updated sharing samples to include sharing large numbers

src/main/webapp/pages/template/page.html, src/main/webapp/resources/js/components/Header/MainNavigation.jsx
Added links to main nav and fixed breadcrumbs
=> Added links to main nav and fixed breadcrumbs

CHANGELOG.md, src/main/webapp/resources/js/components/ant.design/EditableParagraph.jsx, src/main/webapp/resources/js/components/ontology/OntologyInput.jsx, src/main/webapp/resources/js/components/ontology/OntologySelect.jsx, src/main/webapp/resources/js/components/ontology/index.js, src/main/webapp/resources/js/pages/projects/create/CreateProjectDetails.jsx, src/main/webapp/resources/js/pages/projects/samples/add-sample/AddSampleButton.jsx, src/main/webapp/resources/js/pages/projects/settings/components/ProjectDetails.jsx, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/CreateProjectComponent.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectDetailsPage.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/CreateProjectIT.java
All the user to enter a value that is not included in the taxonomy into the organism field when creating a project.
Fixes #1121
=> Allow arbitrary text for organism

src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/ProjectMembersPage.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectMembersPageIT.java
=> Fix flaky tests on Project Members Page

CHANGELOG.md, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/settings/ProjectDetailsAjaxController.java, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIProjectsService.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/projects/ProjectDetailsAjaxControllerTest.java
Make all updates transactional in ProjectDetailsAjaxController and UIProjectsService.
Wait till #1238 is merged before merging this branch as it is based off of that branch.
=> HOTFIX project updates transactional

CHANGELOG.md, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIAnnouncementsService.java, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIMetadataService.java, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIUserGroupsService.java
Fixed updates in UI service classes to use @Transactional annotation to fix scalability issue on large projects >5000 samples.
=> HOTFIX transactional UI service updates

src/main/java/ca/corefacility/bioinformatics/irida/ria/web/models/tables/TableRequest.java, src/main/webapp/resources/js/components/analyses-outputs/SingleSampleAnalysisOutputs.jsx, src/main/webapp/resources/js/components/ant.design/PagedTable/PagedTableContext.js, src/main/webapp/resources/js/components/ncbi/export-table/NcbiExportTable.jsx, src/main/webapp/resources/js/pages/UserGroupsPage/components/UserGroupMembersTable.jsx, src/main/webapp/resources/js/pages/UserGroupsPage/components/UserGroupProjectsTable.jsx, src/main/webapp/resources/js/pages/analysis/components/AnalysisExcelPreview.jsx, src/main/webapp/resources/js/pages/analysis/components/AnalysisTabularPreview.jsx, src/main/webapp/resources/js/pages/projects/list/ProjectsTable.jsx, src/main/webapp/resources/js/pages/projects/settings/components/ReferenceFiles.jsx, src/main/webapp/resources/js/pages/projects/settings/components/associated/ViewAssociatedProjects.jsx, src/main/webapp/resources/js/pages/sequence-files/components/OverRepresentedSequences.jsx, src/main/webapp/resources/js/utilities/antdesign-table-utilities.js, src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/oauth/RemoteAPIAjaxControllerTest.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/services/UIUserGroupsServiceTest.java, src/test/java/ca/corefacility/bioinformatics/irida/web/controller/test/unit/announcements/AnnouncementsAjaxControllerTest.java
Updated `Projects` table to display page size selector for > 1 pages of projects listing.
=> Updated to display page size selector

src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/22.05/user-account-project-subscription.xml
Fixed project subscriptions pr to correctly create project subscription entries for members of user groups.
=> Fix project subscriptions changeset

src/main/webapp/resources/js/pages/projects/linelist/components/Table/Table.jsx, src/main/webapp/resources/js/pages/projects/linelist/components/TableControlPanel/TemplatesPanel/SaveTemplateModal.jsx, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectLineListPage.java
Fixes the issue where could not enter a custom name for a modified metadata template.  Also updated component from a class based component to a functional component.
N/A
=> Fix linelist create template

CHANGELOG.md, pom.xml, src/main/webapp/resources/js/apis/activities/activities.js, src/main/webapp/resources/js/pages/projects/samples/components/FilterByFileModal.jsx
What did you change in this pull request? Provide a description of files changed, user interactions changed, etc. Include how to test your changes.
=> Fixed filtering by file due to bad url

CHANGELOG.md, src/main/webapp/resources/js/pages/admin/components/Admin.jsx, src/main/webapp/resources/js/pages/admin/store.js, src/main/webapp/resources/js/pages/user/components/UserAccountLayout.jsx, src/main/webapp/resources/js/pages/user/components/UserTable.jsx
Fix for rendering the user account details with the admin panel when the navigating from the admin users table.
N/A
=> Fix user routes for admin panel

CHANGELOG.md, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/dto/clients/ClientTableModel.java, src/main/webapp/resources/js/pages/admin/components/clients/listing/ClientsTables.jsx
Fixed sorting of clients table in admin panel.
=> Fix OAuth clients table sorting.

src/main/java/ca/corefacility/bioinformatics/irida/oauth2/OAuth2ResourceOwnerPasswordAuthenticationProvider.java
Captures AuthenticationException when trying to get UsernamePasswordAuthentication during handling of Oauth2 ROPC request.
=> Update Oauth2 ROPC User credentials failure handling

src/main/resources/i18n/messages.properties, src/main/webapp/resources/js/apis/requests.ts, src/main/webapp/resources/js/components/samples/SampleDetailViewer.tsx, src/main/webapp/resources/js/components/samples/components/SampleFiles.tsx, src/main/webapp/resources/js/components/samples/sampleFilesSlice.ts
Added functionality to cancel file uploads.
=> Added functionality to cancel axios requests for uploading files

src/main/java/ca/corefacility/bioinformatics/irida/exceptions/IridaAccountDisabledException.java, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/samples/dto/SampleDetails.java, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UISampleService.java, src/main/resources/i18n/messages.properties, src/main/webapp/resources/js/components/loader/ContentLoading.tsx, src/main/webapp/resources/js/components/samples/SampleDetailViewer.tsx, src/main/webapp/resources/js/components/samples/components/SampleAnalyses.tsx, src/main/webapp/resources/js/components/samples/components/SampleDetails.tsx, src/main/webapp/resources/js/components/samples/components/SampleDetailsModal.tsx, src/main/webapp/resources/js/components/samples/components/SampleDetailsWrapper.tsx, src/main/webapp/resources/js/components/samples/components/SampleFileList.tsx, src/main/webapp/resources/js/components/samples/components/SampleFiles.tsx, src/main/webapp/resources/js/components/samples/components/SampleInfo.tsx, src/main/webapp/resources/js/components/samples/components/SampleMetadata.tsx, src/main/webapp/resources/js/components/samples/components/ViewerHeader.tsx, src/main/webapp/resources/js/components/samples/sampleSlice.ts, src/main/webapp/resources/js/types/irida/index.d.ts, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/components/SampleDetailsViewer.java
What did you change in this pull request? Provide a description of files changed, user interactions changed, etc. Include how to test your changes.
=> Layout fixes for Sample Details Viewer

UPGRADING.md, build.gradle.kts
Bump version number in preparation for release and add upgrading notes for API OAuth2 changes.
=> 22.09 release updates

src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UISampleService.java, src/main/webapp/resources/js/pages/sequencing-runs/components/SequencingRunDetailsPage.jsx
Fixed logic to delete metadata restriction on a field only if it exists. Updated api call for downloading a sequencing file from the sequencing runs details page
=> Sample details refactor fixes

CHANGELOG.md, src/main/webapp/resources/js/pages/analysis/components/AnalysisBioHansel.jsx, src/main/webapp/resources/js/pages/analysis/components/AnalysisOutputFiles.jsx, src/main/webapp/resources/js/pages/analysis/components/AnalysisProvenance.jsx, src/main/webapp/resources/js/pages/analysis/components/AnalysisSettings.jsx, src/main/webapp/resources/js/pages/analysis/components/AnalysisSistr.jsx, src/main/webapp/resources/js/pages/analysis/components/ScrollableSection.tsx, src/main/webapp/resources/js/pages/analysis/components/phylocanvas/ScrollableSection.tsx
Fixed an issue with the rendering of the analysis details pages to allow for scrollable content.
N/A
=> fix: Updated analysis layouts to flex to 100% with scrolling

CHANGELOG.md, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/projects/ProjectSamplesAjaxController.java, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UISampleService.java, src/main/webapp/resources/js/pages/projects/samples/components/RemoveModal.jsx, src/main/webapp/resources/js/pages/projects/samples/services/sample.utilities.js, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/pipelines/LaunchPipelinePage.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectSamplesPage.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ShareSamplesPage.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectSamplesPageIT.java
Fixes issue preventing sharing of locked samples from the UI.
N/A
=> Hotfix remove samples from project

CHANGELOG.md, src/main/java/ca/corefacility/bioinformatics/irida/service/impl/sample/SampleServiceImpl.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectSamplesPageIT.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectShareSamplesIT.java, src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/projects/ProjectSamplesPage.xml, src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/projects/ProjectShareSamples.xml
Server responds with error 500 when trying to call validate sample names endpoint.
Steps to recreate the bug:
- log in as non-admin user
- select a sample from a project
- click share shares
- select a target project
N/A
=> Hotfix: Sharing samples as manager

src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/ProjectMembersPage.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/admin/AdminClientsPage.java
Fixes flaky test on the ProjectMembersPage caused by bad timing in finding an element.
N/A
=> TEST:  Fixes flaky tests in testRemoteProjectManagerPageSetup

src/main/webapp/resources/js/components/project/project-navigation.tsx, src/main/webapp/resources/js/index.tsx, src/main/webapp/resources/js/layouts/app-layout.tsx, src/main/webapp/resources/js/layouts/project-layout.tsx, src/main/webapp/resources/js/redux/endpoints/project.ts, src/main/webapp/resources/js/redux/endpoints/tags.ts
Added project navigation and page layout
N/A
=> Project spa navigation

src/main/java/ca/corefacility/bioinformatics/irida/config/web/IridaUIWebConfig.java, src/main/webapp/resources/js/pages/projects/linelist/sagas/templates.js
Analytics were removed a while ago from IRIDA.  We can add this back in the future if we decide we want to pursue it again.
Unused view handlers for old angular code modals.
N/A
=> Removed old view handlers

settings.gradle.kts
Upgraded Spring Boot to 2.7.6, no changelog entry as I might attempt upgrade to Spring Boot 3 before next release.
=> Spring Boot 2.7.6

.github/workflows/ci-test.yml, src/main/webapp/resources/js/pages/projects/ncbi/create/CreateNcbiExport.tsx
=> Run eslint on changed files when running ci-tests

src/main/webapp/resources/js/apis/export/ncbi.ts, src/main/webapp/resources/js/apis/projects/samples.ts, src/main/webapp/resources/js/apis/requests.ts, src/main/webapp/resources/js/apis/samples/samples.ts, src/main/webapp/resources/js/types/ajax-response.d.ts
Updated post function in `requests.ts` to have typed parameters.
=> Updated post function to accept typed parameters

.github/workflows/ci-test.yml, .github/workflows/codeql-analysis.yml, .github/workflows/grype-scan.yml, .github/workflows/linting.yml, doc/developer/getting-started/index.md
Renamed master branch to main.
* ~~[ ] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.~~
* ~~[ ] Tests added (or description of how to test) for any new features.~~
=> chore: renamed master branch to main

doc/developer/setup/index.md, run-tests.sh, src/main/java/ca/corefacility/bioinformatics/irida/config/repository/IridaApiFilesystemRepositoryConfig.java, src/main/java/ca/corefacility/bioinformatics/irida/config/services/IridaApiServicesConfig.java, src/main/java/ca/corefacility/bioinformatics/irida/repositories/filesystem/IridaFileStorageAwsUtilityImpl.java, src/main/resources/ca/corefacility/bioinformatics/irida/config/filesystem.properties, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/cloud/IridaFileStorageAwsUtilityTest.java
Added functionality to be able to develop and test AWS file storage utility functions locally using localstack. Updated AWS testing to also use localstack. Removed adobe/s3Mock docker run command from run-tests script.
**Instructions to setup on your local machine are in doc/developer/setup/index.md**
Once it's setup on your machine verify the following is working:
1) Uploading/downloading sequence, reference, assembly files
2) Running analyses with the uploaded data and verify the output files are readable/downloadable from the UI
3) Concatenation of files
4) UI displays file data correctly (names, dates, file sizes, etc)
Link to the GitHub …
=> Aws local emulator

build.gradle.kts, src/test/java/ca/corefacility/bioinformatics/irida/service/impl/integration/SequencingRunServiceImplIT.java
Fix tests that were broken due to merging #1486 
=> Fix tests in Development due to delete.from.filesystem tag

.github/dependabot.yml, .github/workflows/ci-test.yml, build.gradle.kts, settings.gradle.kts
This PR updates the springdoc-openapi-gradle-plugin to version 1.9.0
=> Update springdoc openapi gradle plugin

src/main/webapp/package.json, src/main/webapp/pnpm-lock.yaml, src/main/webapp/resources/js/pages/projects/linelist/components/Table/Table.jsx, src/main/webapp/webpack.config.js
=> chore(deps): Update ag-grid to 31.3.4

src/main/webapp/package.json, src/main/webapp/pnpm-lock.yaml
What did you change in this pull request? Provide a description of files changed, user interactions changed, etc. Include how to test your changes.
Updated package.json to resolve rollup to 2.79.2
=> chore(deps): Fixed the version of rollup to fix dependabot error

build.gradle.kts
Update jena-tdb and jena-text to 4.10.0. This pr combines 2 dependabot prs to individually update these packages (PR #1546 and #1547). Capping both versions to 4.10.0 as 5+ requires spring boot 6
~* [ ] User documentation updated …
=> Update: jena-tdb and jena-text to 4.10.0
