phac-nml/irida

packer/scripts/irida-web.sh
The mariadb client package on EPEL is named 'mariadb'
=> Correct MariaDB Client Package Name

src/main/webapp/pages/login.html
Minor aesthetic change, makes the sides of the logo banner carousel on the login page transparent instead of a grey gradient. Also hides the white dots that overlap some logos.
=> Make carousel controls transparent on login page

src/main/java/ca/corefacility/bioinformatics/irida/service/remote/ProjectSynchronizationService.java
I encountered an issue when synchronizing remote projects where FastQC analysis was not being run.  The issue is that when synchronizing the sequencing object, the `processing_state` value of `FINISHED` is also copied over, so file processing is not run.
That is, if file processing was run on **irida-web-development**, and then I sychronize to my local machine, I get the following in the database:
```
+----+---------------------+---------------+------------------+---------------------------------------------+
| id | created_date        | remote_status | processing_state | file_processor                              |
+----+---------------------+---------------+------------------+---------------------------------------------+
|  3 | 2018-06-29 13:36:05 |            14 | FINISHED         | …
```
=> Blank out processing state after project sync

src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/0.23.0/fastqc-version.xml
An attempt to fix #207 by condensing some of the sql commands to one entry.
I think the only improvement that gets made is by moving the **not null** constraint to the code to add the column.
Before, the SQL that gets generated is:
```sql
ALTER TABLE irida_prod_test.analysis_fastqc ADD fastqcVersion VARCHAR(255) NULL;
UPDATE analysis_fastqc SET fastqcVersion="0.10.1";
ALTER TABLE irida_prod_test.analysis_fastqc MODIFY fastqcVersion VARCHAR(255) NOT NULL;
```
This was taking me up to **1.5 hours** to run on our main IRIDA database.
After applying these changes, the SQL that gets generated is:
```sql
ALTER TABLE irida_prod_test.analysis_fastqc ADD fastqcVersion VARCHAR(255) NOT NULL;
UPDATE irida_prod_test.analysis_fastqc SET fastqcVersion = '0.10.1';
```
This takes about **40 mins** for me …
=> Move all updates to one entry in XML

CHANGELOG.md, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/ProjectSamplesController.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectSamplesPageIT.java
Fixes issue where if a user applied a filter to the Project > Samples page and then attempted to select all filtered samples, all samples in the project were selected.  Now only the filtered ones are selected.
Fixes #30 
Fixes #100 
=> Fixes issue where selecting all samples after filtering selected all samples

CHANGELOG.md, doc/developer/getting-started/index.md
Added the CalVer dates to the documentation contributing guide.
This should be tested by running jekyll to generate the documentation (https://irida.corefacility.ca/documentation/developer/getting-started/#building-irida-documentation) and verifying the new section renders properly (should be at http://localhost:4000/developer/getting-started/#release-tags--versioning-scheme).
Fixes #270 
=> Added the calver info to the getting started guide

CHANGELOG.md, src/main/resources/i18n/messages_en.properties, src/main/webapp/pages/projects/templates/linker-modal.tmpl.html
Added a note with link to NGS Linker installation on the Command-line Linker modal.
To test this, visit a Project page then click the Export drop-down, and select Command-line Linker. Verify that the Note appears in the modal. If the Command-line Linker is not installed on your system then you will need to follow the instructions at [https://github.com/phac-nml/irida-linker](https://github.com/phac-nml/irida-linker) to install
Fixes #83 
=> Ngs linker description update

CHANGELOG.md, src/main/webapp/package.json, src/main/webapp/yarn.lock
Updated package.json to use lodash version 4.17.11 to fix security vulnerability.
Fixes #275 
=> Updated lodash to version 4.17.11 to fix security issue

CHANGELOG.md, pom.xml, src/main/webapp/package.json, src/main/webapp/yarn.lock
Signed-off-by: Josh Adam <josh.adam@canada.ca>
This fixes security issue cause by lodash 4.17.10.
N/A
=> Updated to latest lodash to 4.17.11 fix security issue caused by 4.17.10

CHANGELOG.md, pom.xml, src/main/webapp/resources/js/utilities/datatables.utilities.js
Fixes #313 Where importing a metadata excel file with a `.` in the header would cause datatables to error.
None.
=> Hotfix 313 import headers with period

CHANGELOG.md, src/main/webapp/pages/projects/project_samples_metadata_upload.html, src/main/webapp/resources/js/pages/projects/samples-metadata-import/components/saveMetadata.component.js, src/main/webapp/resources/sass/components/datatables.scss
Signed-off-by: Josh Adam <josh.adam@canada.ca>
N/A
=> Fix for datatables sort icons and missing icons on metadata import page.

CHANGELOG.md, src/main/webapp/pages/user/user_details.html, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/user/UserDetailsPage.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/users/UserDetailsPageIT.java
Fixed the email subscription toggle on the user details page.  It was throwing error messages and wasn't allowing users to change their subscriptions.
Note this is a hotfix and should be merged to both master and development.
Fixes #323 
=> fixed the email subscription toggle on the user details page

CHANGELOG.md, pom.xml, src/main/webapp/resources/js/pages/projects/samples/project-samples.js
When we updated jQuery there was a breaking change when calling for the number of elements found after DOM selection.  Previously is was `.size()` now it is just `.length`.
N/A
=> HOTFIX: Fixed jquery issue preventing associated projects from loading

src/main/resources/i18n/messages_en.properties, src/main/webapp/package.json, src/main/webapp/pages/cart.html, src/main/webapp/resources/js/pages/cart/components/CartSamples.jsx, src/main/webapp/resources/js/pages/cart/components/CartTools.jsx, src/main/webapp/resources/js/pages/cart/components/SampleRenderer.jsx, src/main/webapp/resources/js/styles/colors.js, src/main/webapp/webpack.config.dev.js, src/main/webapp/yarn.lock
* Removed using ag-grid as it was too much overkill and replaced with react-window.  This library was chosen because it allow for dynamic sliding DOM windows.
* Moved the clear cart button to the bottom of the page as it looked like it was a clear button for the form.
#192 
=> Cart samples sidebar cleanup

CHANGELOG.md, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysisController.java
Excludes `.xlsx` files from being displayed in the analysis pipelines output preview.
Fix issue #347 
=> Excluding xlsx files from being previewed

.travis.yml, CHANGELOG.md
Upgraded the MariaDB version on the travis CI builds to 10.1.  Apparently it's been failing to install since we did the upgrade in #345, but was conveniently falling back to MySQL.  It stopped falling back today, so this is a version that properly installs.
To test, verify the CI tests are passing and that MariaDB is being installed:
Messages when MariaDB fails to install:
```
The following packages have unmet dependencies:
mariadb-server-10.0 : Depends: mariadb-client-10.0 (>= 10.0.38+maria-1~xenial) but it is not going to be installed
Depends: mariadb-server-core-10.0 (>= 10.0.38+maria-1~xenial) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
...
Starting MariaDB v10.0
...
Job for mysql.service failed because the control process exited …
```
=> Upgraded TravisCI mariadb version to 10.1

src/main/webapp/pages/oauth/access_confirmation.html, src/main/webapp/resources/js/apis/oauth/oauth.js, src/main/webapp/resources/js/components/Header/PageHeader.jsx, src/main/webapp/resources/js/pages/cart/components/CartTools.jsx, src/main/webapp/resources/js/pages/cart/components/CartToolsMenu.jsx, src/main/webapp/resources/js/pages/cart/index.js
Signed-off-by: Josh Adam <josh.adam@canada.ca>
What issue where webpack did not know where to look for code split resources.
=> Cart: tell webpack where the resources are located.

CHANGELOG.md, src/main/java/ca/corefacility/bioinformatics/irida/processing/impl/FastqcFileProcessor.java
Updated the **description** in the **fastqc** analysis results so it contains the version (instead of `{0}`).
```
+----+---------------------+----------------------------------------------+----------------------------+---------------+
| id | createdDate         | description                                  | executionManagerAnalysisId | analysis_type |
+----+---------------------+----------------------------------------------+----------------------------+---------------+
|  9 | 2019-04-25 16:06:16 | Analysis produced by FastQC (Version {0})    | internal-fastqc            | FASTQC        |
| 10 | 2019-04-25 16:06:30 | Analysis produced by FastQC (Version {0})    | internal-fastqc            | FASTQC        |
| 11 | 2019-04-25 16:17:59 | Analysis produced by FastQC (Version 0.11.7) | …
```
=> Add version to description in database

CHANGELOG.md, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/components/agGrid/AgGridColumn.java, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/linelist/LineListController.java, src/main/webapp/resources/js/pages/projects/linelist/reducers/fields.js, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectLineListPageIT.java
It appears the issue with saving linelist templates was the way that the filter variable is being parsed.  Changed this to a string for server parsing.  This lead to having to explicitly ignore the filter for the icon column in the table.
Fixes #369 
=> Fixes issue with creating linelist templates

doc/administrator/upgrades/index.md
Added documentation on how to recover from a database timeout issue when upgrading to IRIDA `19.05`.
None.
* ~[ ] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.~
=> Added database timeout recovery docs

src/main/webapp/package.json, src/main/webapp/resources/js/pages/analyses/analyses-table.js, src/main/webapp/resources/js/pages/projects/samples/project-samples.js, src/main/webapp/yarn.lock
Updated Bootstrap to 3.4.1 to fix security vulnerability.  Needed to fix a bug the htm in popovers.
N/A
**CHANGELOG updated in a previous merge request**
=> Updated to latest bootstrap (3.4.1) to fix security vulnerability

CHANGELOG.md, pom.xml, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/metadata/ProjectSamplesMetadataTemplateController.java
Appears to be an issue that new MetadataTemplateFields are not automatically saved for a new template.  This PR saves the field when it is created and before adding it to the new template.
Fixes #337 
=> Hotfix 337 metadata template creation

CHANGELOG.md, src/main/webapp/bower.json, src/main/webapp/package.json, src/main/webapp/pages/announcements/announcements.html, src/main/webapp/pages/events/events.html, src/main/webapp/pages/index.html, src/main/webapp/pages/samples/_base.html, src/main/webapp/pages/sequencingRuns/_details_base.html, src/main/webapp/resources/js/modules/events/events.js, src/main/webapp/resources/sass/modules/announcements.scss, src/main/webapp/resources/sass/modules/events.scss, src/main/webapp/yarn.lock
Removes `livestampjs` as a project dependency.  Anywhere that was using it (announcements and events) have been replaced with a standard date field.
N/A
Depends on PR #408 
=> Remove livestampjs as a project dependency

CHANGELOG.md, src/main/webapp/bower.json, src/main/webapp/pages/sequencingRuns/run_files.html
Remove noty from bower.  The only page it was loaded on was `run_files.html`.  There is nothing for noty on that page.
N/A
Depends on PR #409 
=> Remove noty from bower

CHANGELOG.md, src/main/java/ca/corefacility/bioinformatics/irida/service/impl/CRUDServiceImpl.java, src/test/java/ca/corefacility/bioinformatics/irida/service/impl/unit/user/UserServiceImplTest.java
Removed an unnecessary `exists` call in `CrudServiceImpl#updateFields`.  The call was there since the time we weren't using reflection or JPA to update the objects.  It was causing some weird Hibernate caching issues when running in a transaction.  It wasn't needed anyway since earlier in the method we were already reading the object so clearly it must exist.
N/A
~* [ ] User documentation updated for UI or technical changes.~ Not needed
=> Remove unnecessary exists in update

CHANGELOG.md, doc/_includes/tutorials/common/samples/galaxy-export.md
Added a link to installation instructions for the Galaxy export (import) tool.
The majority of the documentation is in the tool's github repo (part of PR https://github.com/phac-nml/irida-galaxy-importer/pull/10, direct link to documentation [here](https://github.com/phac-nml/irida-galaxy-importer/blob/b692f8e0c69a2a457fc7198a400a5594595df360/README.md). This just adds a link to the github repo.)
Fixes issue #276 
=> Added link to Galaxy export tool

src/main/webapp/resources/js/pages/projects/list/ProjectsTable.jsx
Removed extra / character in projects link in projects table
Note: Changelog is not updated as this is not currently present in a release.
=> Fix extra / in projects link from projects table

UPGRADING.md
There was no upgrading message in the 19.09 release.  This adds the message about database changes.  Note this needs to be merged into both `development` and `master`.
No tag updates or official releases needed since it's just for display in the repo.
N/A
=> Hotfix - Missing upgrading message

CHANGELOG.md, pom.xml, src/main/resources/configuration.properties
Hotfix to fix the default server language.  It was accidentally released with `fr`.  This wouldn't have seen any user issues since there was no `fr` translation file, except some people may have seen a google translate popup.
N/A
=> Fixed default server language

CHANGELOG.md, src/main/java/ca/corefacility/bioinformatics/irida/exceptions/ConcatenateException.java, src/main/java/ca/corefacility/bioinformatics/irida/processing/concatenate/SequencingObjectConcatenator.java, src/main/java/ca/corefacility/bioinformatics/irida/processing/concatenate/impl/SequenceFilePairConcatenator.java, src/main/java/ca/corefacility/bioinformatics/irida/processing/concatenate/impl/SingleEndSequenceFileConcatenator.java, src/test/java/ca/corefacility/bioinformatics/irida/processing/concatenate/SequencingObjectConcatenatorFactoryTest.java, src/test/java/ca/corefacility/bioinformatics/irida/processing/concatenate/impl/SequenceFilePairConcatenatorTest.java, src/test/java/ca/corefacility/bioinformatics/irida/processing/concatenate/impl/SingleEndSequenceFileConcatenatorTest.java
Fixed the file concatenation methods to work with `.fastq.gz` data.  Previously the file extension was hardcoded as `.fastq` so the file processing would fail.  Also the method we were using to concatenate the files didn't work with gzipped data.
To test, upload multiple files to a sample, wait for them to file process, then concatenate from the sample/files page.  Then change the `file.processing.decompress=` value in your `/etc/irida/irida.conf` file and try the same again.
Fixes #481 
=> Concatenate zipped fastq

CHANGELOG.md, src/main/webapp/resources/js/modules/cart/irida.cart.js, src/main/webapp/resources/js/pages/pipelines/pipeline.launch.js
Fixes issue where once a pipeline was kicked off, the "Let the pipeline run" button was not working.  It was supposed to empty the cart and redirect the browser to the projects listing page.  This broke during the cart refactor.
Fixes #411 
=> Fixed issue with "Let the pipeline run" button not working.

CHANGELOG.md, src/main/webapp/bower.json, src/main/webapp/entries.js, src/main/webapp/package.json, src/main/webapp/pages/login.html, src/main/webapp/pages/template/page.html, src/main/webapp/resources/js/app.js, src/main/webapp/resources/js/pages/samples/sample-files.js, src/main/webapp/yarn.lock, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/analysis/AnalysisDetailsPageIT.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectSyncPage.java
Removed the bower dependency `for angular-bootstrap` and replaces it with a yarn dependency for `angular-ui-bootstrap`.
#125 
=> Remove angular bootstrap from bower

CHANGELOG.md, src/main/webapp/resources/js/components/galaxy/GalaxyApp.jsx, src/main/webapp/resources/js/components/galaxy/GalaxyDetailsForm.jsx
Fixed issue from Matt Walker where the checkbox to "Automatically create collection" could not be unchecked.
N/A
=> Fix galaxy create collection checkbox

CHANGELOG.md, pom.xml, src/main/webapp/pages/cart.html, src/main/webapp/pages/template/page.html, src/main/webapp/resources/js/pages/cart/components/Cart.jsx
Issue report by Nabil on Gitter, where the cart page does not render at full height.
Before:
After:
N/A
=> Fixed issue where cart page does not display at full height.

.travis.yml, CHANGELOG.md, src/main/webapp/package.json, src/main/webapp/yarn.lock
Chrome in Travis CI Xenial image updated to 78, this PR updates to a corresponding working chromedriver version.
=> Update chromedriver to fix Travis CI tests

CHANGELOG.md, src/main/webapp/package.json, src/main/webapp/yarn.lock
Reverts phac-nml/irida#531
Travis CI Xenial image appears to have downgraded chrome version back to 76
=> Revert "Update chromedriver to fix Travis CI tests"

CHANGELOG.md, src/main/webapp/wepack.config.prod.js
Re-enabled minification in webpack config with options that don't encode unicode strings. terser-webpack-plugin options are the same that webpack uses in v4.41.2 with the addition of `ascii-only: true` which tells it to leave alone ascii strings. Default config was converting unicode strings. https://github.com/webpack/webpack/blob/v4.41.2/lib/WebpackOptionsDefaulter.js
=> Enable webpack minification

src/main/java/ca/corefacility/bioinformatics/irida/model/export/NcbiBioSampleFiles.java, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/ProjectExportController.java, src/main/java/ca/corefacility/bioinformatics/irida/service/impl/AnnouncementServiceImpl.java, src/main/java/ca/corefacility/bioinformatics/irida/service/impl/CRUDServiceImpl.java, src/main/java/ca/corefacility/bioinformatics/irida/service/impl/IridaClientDetailsServiceImpl.java, src/main/java/ca/corefacility/bioinformatics/irida/service/impl/user/UserGroupServiceImpl.java, src/test/java/ca/corefacility/bioinformatics/irida/service/export/ExportUploadServiceTest.java, src/test/java/ca/corefacility/bioinformatics/irida/service/export/NcbiExportSubmissionServceTest.java, src/test/java/ca/corefacility/bioinformatics/irida/service/export/NcbiExportSubmissionServiceTest.java
Changed file collections in NCBI export object to Sets to keep to JPA standard.  This removes the hibernate imports for the collection types.  Better for these files to be sets anyway.
I've tested running this code against NCBI's test FTP server and confirmed the uploads are working as expected.
N/A
=> Changed NCBI export collections to sets

src/test/java/ca/corefacility/bioinformatics/irida/service/impl/integration/SequencingObjectServiceImplIT.java
Added a wait to SequencingObjectServiceImplIT to help ensure the seq file in the test is settled before reading
N/A
=> adding wait to service test to ensure seq file is settled before reading

CHANGELOG.md, UPGRADING.md
Added a change to the hibernate.dialect to mysql 5.5.  This is already set in the default server conf files, but if someone added it to their `/etc/irida/irida.conf` file it could cause issues in the future if they don't update it.
N/A
=> Added mysql5.5 dialect change to upgrading guide

CHANGELOG.md, src/main/webapp/pages/user/list.html
The users list page was using the wrong i18n tag.  Fixed this to use the users title.
n/a
=> Fixed the title of the users list page

src/main/java/ca/corefacility/bioinformatics/irida/ria/web/models/tables/TableRequest.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/analysis/AnalysesUserPage.java
Changed the search term to be trimmed when it's set for the `TableRequest` instead of when it's requested.  The issue was that if there's no search term and the getter is called, it's trying to trim it then which would throw a nullpointer.
Fixes #605 
~* [] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.~ Not bothering because we caused this error with the hotfix.  Not really a change.
=> Changed trim for tablerequests

CHANGELOG.md, src/main/webapp/entries.js, src/main/webapp/pages/sequenceFiles/file_overrepresented.html, src/main/webapp/resources/js/pages/sequence-files/overrepresented.js
Just remove DataTables and left as a regular table.  Looking through production data, these tables do not get that large.
#413 
=> Remove DataTables from overrepresented sequences for sequencing files

src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysisAjaxController.java, src/main/resources/i18n/messages.properties, src/main/webapp/resources/js/pages/analysis/components/settings/AnalysisSampleRenderer.jsx, src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/analysis/AnalysisAjaxControllerTest.java
Fixed 500 error being thrown in console when visiting an analysis samples page from which a sample had been deleted. Updated samples page to display samples which have been deleted and made styling changes to the sample name.
To test:
1. Add sample to a project and run an analysis
2. Once the analysis is completed visit the analysis > settings > samples tab and see which samples the analysis was run with. The sample name should be clickable and there should be no 500 error thrown in the console for the browser
3. Go to the project you used the sample from and delete it.
4. Visit the analysis > settings > sample tab
5. The sample name should …
=> Analysis/ sample renderer undefined fix

src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysesAjaxController.java, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysisAjaxController.java, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysisController.java, src/main/webapp/pages/analysis.html, src/main/webapp/resources/js/contexts/AnalysisContext.js, src/main/webapp/resources/js/pages/analysis/components/AnalysisSteps.jsx, src/main/webapp/resources/js/pages/analysis/components/outputs/OutputFilePreview.jsx, src/main/webapp/yarn.lock
Fixed issue when a tree file was not found and an exception was thrown on the server side which caused the UI to crash when loading the phylogenetic tree page. Added duration to AnalysisSteps description which displays the analysis duration under the current step. Refactored some variables in AnalysisSteps component.
**To test properly start up irida with the production profile:**
1) Add samples to a project, add to cart, and run SNVPhyl
2) Wait a few minutes and view the analyses table. It should no longer say "a few seconds" but display the actual duration
3) Click on the analysis in the analyses table to view the Analysis. The analysis …
=> Updated analysis duration to display correctly when not in completed or error state

src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysisAjaxController.java
Updated AnalysisAjaxController so that a user can now share single end analyses with other projects.
=> Type single end analyses can now be shared with other projects

src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/components/AntTable.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/AdminUsersPage.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/users/AdminUsersPageIT.java
When designing the tests for this table, I forgot to take into account that I was checking a column of dates was sorted.  This fixes the test by first ensuring the date is formatted properly, and then converting it to milliseconds before checking to see if the column is sorted properly.
N/A
=> Fixed checking to see if table sorted by modified date

src/main/webapp/resources/js/components/Header/GalaxyAlert.jsx
The link icon on the Galaxy Alert was missed during the last upgrade.  This fixes it.
N/A
N/A
=> 🔨️ Fixed missing icon on GalaxyAlert

src/main/webapp/pages/projects/project_samples.html
Because the project samples filter is loaded into a modal separate from webpack builds (it is loaded using bootstrap itself), they are not added to the `window.translations` array.  This manually adds them.
N/A
=> Added missing translations for project samples date range filter

CHANGELOG.md, src/main/java/ca/corefacility/bioinformatics/irida/processing/impl/AutomatedAnalysisFileProcessor.java
Added default analysis priority when the project doens't have one set.  Previously this would throw a nullpointerexception.  I think it only would happen in the dev database, but worth protecting anyway.
N/A
=> Analysis Priority when project setting is null

src/main/java/ca/corefacility/bioinformatics/irida/model/sequenceFile/Fast5Object.java, src/main/java/ca/corefacility/bioinformatics/irida/processing/FileProcessor.java, src/main/java/ca/corefacility/bioinformatics/irida/processing/impl/AutomatedAnalysisFileProcessor.java, src/main/java/ca/corefacility/bioinformatics/irida/processing/impl/DefaultFileProcessingChain.java, src/main/java/ca/corefacility/bioinformatics/irida/processing/impl/FastqcFileProcessor.java, src/main/java/ca/corefacility/bioinformatics/irida/processing/impl/GzipFileProcessor.java, src/test/java/ca/corefacility/bioinformatics/irida/processing/impl/unit/AutomatedAnalysisFileProcessorTest.java, src/test/java/ca/corefacility/bioinformatics/irida/processing/impl/unit/FastqcFileProcessorTest.java
Disabling the FastQC file processor for zipped fast5 files (`.fast5.tar.gz`).  Previously it was failing "gracefully", but that was creating qc entries for the failure even though it was working as intended.  Now it just skips the processor for that file type.
N/A
=> Disbale fastqc zipped

CHANGELOG.md, src/test/java/ca/corefacility/bioinformatics/irida/model/SampleTest.java, src/test/java/ca/corefacility/bioinformatics/irida/model/UserTest.java, src/test/java/ca/corefacility/bioinformatics/irida/model/sample/metadata/unit/MetadataEntryTest.java, src/test/java/ca/corefacility/bioinformatics/irida/repositories/filesystem/SequenceFileRepositoryImplTest.java, src/test/java/ca/corefacility/bioinformatics/irida/repositories/relational/auditing/UserRevListenerIT.java, src/test/java/ca/corefacility/bioinformatics/irida/service/impl/integration/AnnouncementServiceImplIT.java, src/test/java/ca/corefacility/bioinformatics/irida/service/impl/integration/GenomeAssemblyServiceImplIT.java, src/test/java/ca/corefacility/bioinformatics/irida/service/impl/integration/ProjectServiceImplIT.java, src/test/java/ca/corefacility/bioinformatics/irida/service/impl/integration/SequencingObjectServiceImplIT.java, src/test/java/ca/corefacility/bioinformatics/irida/service/impl/integration/SequencingRunServiceImplIT.java, src/test/java/ca/corefacility/bioinformatics/irida/service/impl/integration/analysis/submission/AnalysisSubmissionServiceImplIT.java, src/test/java/ca/corefacility/bioinformatics/irida/service/impl/unit/CRUDServiceImplTest.java, src/test/java/ca/corefacility/bioinformatics/irida/service/impl/unit/ProjectServiceImplTest.java, src/test/java/ca/corefacility/bioinformatics/irida/service/impl/unit/util/impl/SequenceFileUtilitiesTest.java
Removed any uses of `new Long()` as it's deprecated in Java 9.  Updated to using `Long.valueOf(#)` or `#L` which is better supported.  This removes some build warnings in IntelliJ.
To test this PR, verify that the intergration tests complete successfully on TravisCI.
N/A
=> Removed deprecated Long constructor

CHANGELOG.md, src/main/webapp/package.json, src/main/webapp/yarn.lock
Upgraded webpack-dev-esrver to fix websocket-extensions from 0.1.3 to 0.1.4
N/A
=> Upgrade webpack dependencies to fix issue with websocket-extensions from 0.1.3 to 0.1.4

CHANGELOG.md, pom.xml, src/main/java/ca/corefacility/bioinformatics/irida/model/remote/RemoteStatus.java, src/main/webapp/package.json, src/main/webapp/yarn.lock, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/announcements/AnnouncementControlPage.java
Changed the `RemoteStatus` constructor to `protected` instead of `private`.  Hibernate had some changes with an update that changes the way proxies are created.  Apparently they have issues with `private` default constructors.  This appeared when trying to run an analysis with remote synchronized data.
Note this is a hotfix merge and must be merged into both `master` and `development`.
Fixes #744 
=> Hotfix: Changed RemoteStatus constructor to `protected`

CHANGELOG.md, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/oauth/OltuAuthorizationController.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/oauth/OltuAuthorizationControllerTest.java
Fixed an issue where paths were being appended by string concatenation in the OAuth2 flow instead of using a URI builder.  If someone had a trailing slash in the `server.base.url` (ex `http://localhost:8080/`) it could cause a double slash in the redirect URI.  This would cause the OAuth2 redirect verification to fail.
To test, in your `/etc/irida/web.conf` file try adding a slash to the end of the `server.base.url`, then using the test database try connecting to your own machine by a remote API.
Fixes #677 
=> Fix OAuth2 redirect url builder

CHANGELOG.md, pom.xml, src/main/java/ca/corefacility/bioinformatics/irida/exceptions/LinkNotFoundException.java, src/main/java/ca/corefacility/bioinformatics/irida/service/remote/GenomeAssemblyRemoteService.java, src/main/java/ca/corefacility/bioinformatics/irida/service/remote/ProjectSynchronizationService.java, src/main/java/ca/corefacility/bioinformatics/irida/service/remote/impl/GenomeAssemblyRemoteServiceImpl.java, src/test/java/ca/corefacility/bioinformatics/irida/service/ProjectSynchronizationServiceTest.java
Allowing IRIDA 20.09 to synchronize with older versions which do not yet have the assemblies available in the REST API.
Fixes #819 
=> Syncing with older versions of IRIDA

CHANGELOG.md, pom.xml, src/main/webapp/package.json, src/test/java/ca/corefacility/bioinformatics/irida/web/controller/test/integration/project/RESTProjectAnalysisControllerIT.java
Removed the `javax.interceptor-api` maven dependency from our pom file.  It appears that version of the library was accidentally released and is actually invalid <https://github.com/eclipse-ee4j/interceptor-api/issues/4>.  
It was added as an artifact to help with the javadoc build, but doesn't appear to even be needed anymore.  It imported a library that was used in one place in the program, but I refactored it out.
Note this is a hotfix and should also be merged into `development`.  Existing installs of `20.09.2` do not need to be upgraded, this only affects building IRIDA from source.
N/A.  Reported by @JeffreyThiessen and on Gitter.
~* [ ] Tests added (or description of how to test) for any new …
=> HOTFIX: Removed javax.interceptor-api Maven artifact.

README.md
Switched the badge for the CI build status to link to our GitHub actions builds.
N/A
=> adding the github acitons CI badge to the readme

.github/workflows/ci-test.yml, README.md
Added link to CI results when clicking badge.
In a later change this also changed the maven dependency caching to separate by profile.  Different profiles have different dependencies in some cases and were getting missed by the cache.
N/A
=> Added link to GitHub Actions CI in readme badge

CHANGELOG.md, pom.xml, src/main/webapp/pages/projects/settings/pages/associated.html, src/main/webapp/pages/projects/settings/pages/details.html, src/main/webapp/pages/projects/settings/pages/remote.html
Found a number of broken CSS bundle hrefs in the project settings pages.  They didn't include the context paths and just had a regular `href=/somewhere`.  Added the context paths with thymeleaf to these paths.
FIxes #905 
=> Fix project settings css hrefs

src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UICartService.java, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/sessionAttrs/Cart.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/services/UICartServiceTest.java
Currently if you:
1.  Add samples to the cart
2.  Go to the cart page and click the "Empty Cart" button on the bottom of the right side panel, the samples get removed
3.  If you try to add those same samples, you get an error that the samples cannot be added because a sample of the same name already exists in the cart.
This happens because the "Cart" extends HashMap and I only cleared the map, what I forgot was that there was a HashMap inside that contains the sample id and sample names for fast look ups (for seeing if the name is already in the cart).  This PR clears that when the cart is empty.  As well I added a bunch of testing for the cart service itself.
N/A
*   [ ] ~CHANGELOG.md (and UPGRADING.md if …
=> Fix issue with clearing samples from the cart

doc/administrator/galaxy/index.md, doc/developer/getting-started/index.md
Fix minor typo in IRIDA's developer documentation. Added "assembly" on the list of directories mentioned and included a sentence about adding directories manually in the guide for setting up Galaxy as these directories do not automatically exist.
=> Documentation fix

src/main/java/ca/corefacility/bioinformatics/irida/model/sample/StaticMetadataTemplateField.java, src/main/java/ca/corefacility/bioinformatics/irida/model/sample/metadata/PipelineProvidedMetadataEntry.java, src/main/java/ca/corefacility/bioinformatics/irida/model/workflow/analysis/Analysis.java, src/main/java/ca/corefacility/bioinformatics/irida/model/workflow/submission/IridaWorkflowNamedParameters.java, src/main/java/ca/corefacility/bioinformatics/irida/service/remote/ProjectSynchronizationService.java, src/test/java/ca/corefacility/bioinformatics/irida/service/ProjectHashingServiceIT.java, src/test/resources/ca/corefacility/bioinformatics/irida/test/integration/TableReset.xml
Added `hashCode` functions for 2 classes `StaticMetadataTemplateField.java` and `IridaWorkflowNamedParameters`.  Without the hashcode function it was breaking the full project hashing for any analyses that had `PipelineProvidedMetadata`.  Without `hashCode` being implemented, it the hash would change every time you ran the hash function.
Related to #392 
=> Fixed hashing

CHANGELOG.md, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/ProjectSamplesController.java, src/main/webapp/resources/js/pages/projects/samples/project-samples.js
Updated the jQuery load function and moved the sampleIds from a query param into a data object (the optional second argument passed to load) which turns this into a POST request.  This should allow the request to handle a larger number of sample identifier.
Fixes #916
=> Fix issue moving a large number of samples between project

CHANGELOG.md, pom.xml, src/main/webapp/resources/js/pages/analysis/components/AnalysisTabularPreview.jsx
Fixed bug which wouldn't let user preview more than 5 lines of an analysis tabular result file by removing max-height of the table in which the tab file is displayed.
Fixes #926 
=> HOTFIX: Fix tabular result viewer

CHANGELOG.md, src/main/webapp/package.json, src/main/webapp/webpack.config.js, src/main/webapp/yarn.lock
Fixed issue with css bundle files not being written due to a conflict between style-loader and minicssextractplugin
=> Fixed webpack not outputting css files

src/main/webapp/resources/js/pages/visualizations/phylogenetics/components/phylocanvas/phylocanvas.component.js
If you use any reference file starting with line, other than `>reference`,  the for loop which adds data to the leaves of the tree would throw an error `can't convert undefined to object.`, basically happens when it tries to set `leaf.data = metadata['anything other than reference'];` - the result would be that `leaf.data = undefined` and the phylocanvas plugin would break when trying to run `tree.load(newick)`.
I  added an `if statement` to check the existence of leaf.label as a key in metadata object, which is the case for the samples and when it doesn't, as the case of a custom named reference e.g `>Chromosome`/`NC_000962.3` for my case, it would lookup the contents of `metadata.reference`.
https://github.com/phac-nml/irida/issues/941
=> Metadata Phylogeny-tree Advanced Visualisation fix 

CHANGELOG.md, pom.xml, src/main/java/ca/corefacility/bioinformatics/irida/web/controller/api/projects/RESTProjectSamplesController.java, src/test/java/ca/corefacility/bioinformatics/irida/web/controller/test/integration/project/ProjectSamplesIT.java, src/test/java/ca/corefacility/bioinformatics/irida/web/controller/test/unit/project/RESTProjectSamplesControllerTest.java
Added an ownership flag API endpoint copying samples to another project via the REST API.  Add ownership flag as URL variable with `?ownership=true/false`.  Default is `false`
N/A
=> HOTFIX: Added ownership flag to copying sample to project in REST API

.gitignore, doc/.gitignore
Moved ignoring the apidocs from the `/docs` directory gitignore down to the project root gitignore.  On deploying the new docs it was accidentally ignoring the apidocs changes.
N/A
=> Changed git ignore for apidocs down to the main gitignore file

CHANGELOG.md, src/main/webapp/resources/js/pages/projects/samples/linker/Linker.jsx
Added a conditional check that the html element exists before rendering the Linker component.
Fixes #958
=> Fix for samples not rendering on project samples page when config property ngsarchive.linker.available set to false

CHANGELOG.md, UPGRADING.md, pom.xml, src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/21.01/all-changes.xml, src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/21.01/remove-sample-metadata-entry.xml
Removing the `sample_metadata_entry` tables that should have been dropped in the 21.01 update.  They should have been removed in the `metadata-entry-refactor` changeset.  The tables are no longer used in the model.
Note this is a hotfix upgrade and should be merged to both `master` and `development` branches.
N/A
=> Hotfix remove unnecessary tables

src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIProjectReferenceFileService.java, src/test/java/ca/corefacility/bioinformatics/irida/service/impl/unit/ProjectServiceImplTest.java
Fixed issue of the referenceFile being saved twice to the referenceFileRepository when adding a reference file to a project.
**To test run either the dev or production profile of IRIDA in Intellij in debug mode:**
1) Set breakpoint on either line 38 or 39 in the `countSequenceFileLengthInBases` method within `BioJavaSequenceFileUtilitiesImpl`.
2) Upload a reference file within a project
3) Stepping through the debugger should only have you land on the breakpoint above 1 time with the file that is created in the /tmp directory
**To test out the double saving to the referenceFileRepository try the above on the `development` branch. Here you …
=> Fix reference file upload

CHANGELOG.md, doc/developer/rest/index.md, src/main/java/ca/corefacility/bioinformatics/irida/web/assembler/resource/sample/SampleMetadataResponse.java, src/main/java/ca/corefacility/bioinformatics/irida/web/controller/api/projects/RESTProjectSamplesController.java, src/main/java/ca/corefacility/bioinformatics/irida/web/controller/api/samples/RESTSampleMetadataController.java, src/test/java/ca/corefacility/bioinformatics/irida/web/controller/test/integration/sample/RESTSampleMetadataControllerIT.java, src/test/java/ca/corefacility/bioinformatics/irida/web/controller/test/unit/project/RESTProjectSamplesControllerTest.java, src/test/java/ca/corefacility/bioinformatics/irida/web/controller/test/unit/samples/RESTSampleMetadataControllerTest.java, src/test/resources/ca/corefacility/bioinformatics/irida/web/controller/test/integration/sample/RESTSampleMetadataControllerIT.xml
Added a REST endpoint to request a full project's sample metadata at the same time.  This should help with performance issues when reading large amounts of metadata at the same time.  This endpoint may be slow for large projects, but if you need to read a full project anyway should be faster than requesting for each individual sample.
Also beefed up the testing for all the methods in the metadatacontroller.
N/A
This was originally being built as a hotfix in #974.  Now just going into development.
=> Single request all project metadata

CHANGELOG.md, pom.xml, src/main/java/ca/corefacility/bioinformatics/irida/service/remote/impl/Fast5ObjectRemoteServiceImpl.java, src/main/webapp/package.json, src/test/java/ca/corefacility/bioinformatics/irida/service/ProjectSynchronizationServiceTest.java
Added an error thrown from the fast5 remote repository when the link for fast5 data isn't available.  This would happen if syncing with an older version of IRIDA.
Note this is a hotfix PR and should also be merged to `development`.
N/A
=> Hotfix: Throw link error when fast5 not available

CHANGELOG.md, pom.xml
Excluded a few directories from the war file build as they're unnecessary for deployment.  With a yarn upgrade the war file was building >400MB.
N/A
=> Excluding unnecessary directories from war file build

CHANGELOG.md, pom.xml, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIRemoteAPIService.java, src/main/webapp/resources/js/pages/projects/settings/components/ProjectSynchronizationSettings.jsx
Updated creating of remote project to be set sync status as `UNSYNCHRONIZED` if the frequency is set to `NEVER`. Updated UI to enable sync buttons if a project is in `UNSYNCHRONIZED` state.
**To Test:**
1) Create a project
2) Synchronize Remote Project with a frequency of `NEVER`
3) Go into the remote project -> settings -> remote page
4) The `Force Sync` and `Sync Now` buttons should both be enabled even though the project is in `UNSYNCHRONIZED` state
Things for the developer …
=> HOTFIX: Enable sync now button on project synchronization settings page if in UNSYNCHRONIZED state

CHANGELOG.md, src/main/webapp/resources/js/components/Header/MainNavigation.jsx
Added a link to the users list for IRIDA managers.  Managers need to be able to create users, and the link to the list and creation pages were accidentally removed in the refactor of the main navigation.
Fixes #1024 
=> Hotfix - add user list link for manager

src/main/java/ca/corefacility/bioinformatics/irida/web/spring/view/FastaView.java
Casting the model `resource` to `ResponseResource` in FastaView.  This is similar to the other view classes, it looks like this one got missed.  Prior to this fix if you requested the content of an assembly you got the error:
```
class ca.corefacility.bioinformatics.irida.web.assembler.resource.ResponseResource cannot be cast to class ca.corefacility.bioinformatics.irida.model.irida.IridaSequenceFile
```
Related to #978 
=> Casting to ResponseResource in FastaView

CHANGELOG.md, UPGRADING.md, doc/administrator/galaxy/index.md, doc/administrator/galaxy/pipelines/phylogenomics/index.md, doc/administrator/galaxy/pipelines/test/snvphyl/snvphyl_workflow.ga, docker/base-image/Dockerfile, docker/base-image/galaxy/irida-tools.yml, docker/integration-testing/Dockerfile, docker/virtual-machine/Dockerfile, docker/virtual-machine/data/tools-list.yml, pom.xml, run-tests.sh, src/main/resources/ca/corefacility/bioinformatics/irida/config/workflows.properties, src/main/resources/ca/corefacility/bioinformatics/irida/model/workflow/analysis/type/workflows/SNVPhyl/1.2.3/irida_workflow.xml, src/main/resources/ca/corefacility/bioinformatics/irida/model/workflow/analysis/type/workflows/SNVPhyl/1.2.3/irida_workflow_structure.ga, src/main/resources/ca/corefacility/bioinformatics/irida/model/workflow/analysis/type/workflows/SNVPhyl/1.2.3/messages_en.properties
* Updates SNVPhyl to version `1.2.3` (from `1.2.2`) which includes all updated tools which can all be properly installed in Galaxy.
* Updates the IRIDA/Galaxy Docker image to include this new version of SNVPhyl and also updates from Galaxy 20.05 to 20.09 (the latest Galaxy Docker image).
* Updates the integration test suite to use this newer Docker image with the latest SNVPhyl pipeline.
In order to test this out, you can install the newest IRIDA/Galaxy Docker by the command:
```bash
docker run -d -p 48888:80 -v /path/to/irida/data:/path/to/irida/data phacnml/galaxy-irida-20.09
```
Where `/path/to/irida/data` is the location of your IRIDA data directories and `48888` is the port that Galaxy should run on.
Once the IRIDA/Galaxy Docker container is running you can connect IRIDA to this …
=> hotfix/snvphyl 1.2.3

CHANGELOG.md, pom.xml, src/main/webapp/resources/js/components/project-members/ProjectMembersTable.jsx, src/main/webapp/resources/js/components/project-user-groups/ProjectUserGroupsTable.jsx, src/main/webapp/resources/js/components/roles/ProjectRole.jsx, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/ProjectMembersPage.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectSyncPage.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectMembersPageIT.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectUserGroupsPageIT.java
This hotfix fixes bug preventing a manager on a remote project from adding and removing members/groups.
**To test:**
1) Create a synchronized project
2) Add a user to the sync'd project and give them a `Manager` role
3) Login as the manager user from above
4) In the remote `Project -> Settings -> Members` you should be able to see the `Add Project Member` button and be able to add a user to the project.
5) In the remote `Project -> Settings -> Groups` you should be able to see the `Add User Group` button and be able to add a user group to the project.
6) You should also be able to remove the users and groups added above
Link to the GitHub …
=> HOTFIX: Remote project manager members/groups permissions

CHANGELOG.md, pom.xml, src/main/webapp/resources/js/pages/projects/settings/components/metadata/MetadataTemplateManager.jsx, src/main/webapp/resources/js/pages/projects/settings/components/metadata/MetadataTemplates.jsx
Fixes bug that resulted from old urls still in the create metadata templates, and an incorrect variable `isLoading` instead of `isFetching`
N/A
=> HOTFIX: Fixed issue with metadate template redirect

CHANGELOG.md, src/main/resources/i18n/messages.properties, src/main/webapp/resources/js/pages/projects/create/CreateProjectDetails.jsx, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/CreateProjectComponent.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/ProjectsPage.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/CreateProjectIT.java
Fixes an issue where the length of the project name was not checked on creation.
The validation now checks:
* Length
* Restricted characters
* Required
N/A
* ~~[ ] Tests added (or description of how to test) for any new features.~~
* ~~[ ] User documentation updated for UI or technical changes.~~
=> Fix for verifying the project name length

CHANGELOG.md, src/main/webapp/resources/js/pages/projects/settings/components/metadata/MetadataTemplateCreate.jsx
Force the refresh of the metadata templates list allows for the first template to be created to be displayed nicely.
N/A
=> Fix create first metadata template

CHANGELOG.md, src/main/java/ca/corefacility/bioinformatics/irida/service/impl/sample/SampleServiceImpl.java, src/test/java/ca/corefacility/bioinformatics/irida/service/impl/unit/sample/SampleServiceImplTest.java
Updating the Sample modified date whenever metadata is updated on a sample.  Previously this was always updated because the metadata map was a property of the sample.  Now since its updated separately, the modified date needs to be manually bumped in the update method.
N/A
=> Updating Sample modified date when metadata is updated

CHANGELOG.md, src/main/webapp/package.json, src/main/webapp/yarn.lock
Fixes dependabot warning for `set-value` by forcing it in the package.json file.
N/A
=> Force using a set-value above 4.0.1

src/main/java/ca/corefacility/bioinformatics/irida/web/controller/api/RESTAnalysisSubmissionController.java
An endpoint went missing during the Swagger enhancement.
N/A
=> Fix for missing RESP API endpoint

CHANGELOG.md, src/main/java/ca/corefacility/bioinformatics/irida/repositories/sample/MetadataEntryRepositoryImpl.java, src/main/java/ca/corefacility/bioinformatics/irida/repositories/sample/MetadataFieldRepositoryImpl.java
In systems with large amounts of metadata, the queries for retrieving all `metadata_field` for a given project were slowing down.  This appeared to be occurring with the double `INNER JOIN` query between `metadata_entry`, `metadata_field`, and `project_sample`.
This PR breaks that query down into 2 simpler queries:
* First one that gets the field IDs for a project in a query joining `metadata_entry` and `project_sample`
* Second that loads the full `metadata_field` given those ids.
The previous query was sometimes running in the 10s of seconds to query the metadata and fields, this updated code runs in <1s for all projects tested.
N/A …
=> Updated metadata queries for performance

CHANGELOG.md, src/main/java/ca/corefacility/bioinformatics/irida/repositories/specification/ProjectSampleSpecification.java, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/ProjectSamplesController.java, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/dto/ExportToFileModel.java, src/main/webapp/resources/js/pages/projects/samples/project-samples.js, src/main/webapp/resources/js/utilities/file-utilities.js
**Previously**: When filter by file was applied and the user tried to export the samples to excel or csv, the download would contain all the samples in the project.
**Fix**:  By default when filter by file is applied the filtered samples are selected. I am using this system to send the selected sample ids to the server and filtering the samples based on this list.
Fixes #985 
=> Fixes filter by file exports all samples

src/main/java/ca/corefacility/bioinformatics/irida/config/web/IridaUIWebConfig.java
Made a mistake when I wrote which profile to use to prevent caching of the web packer stuff by Thymeleaf.  This PR allows it to not cache in development.
N/A
N/A
=> Fixed issue where could not reload dev changed UI files

CHANGELOG.md, src/main/webapp/package.json, src/main/webapp/resources/js/pages/projects/linelist/components/Toolbar/Toolbar.jsx, src/main/webapp/resources/js/pages/projects/samples-metadata-import/components/SampleMetadataImportComplete.jsx, src/main/webapp/resources/js/pages/projects/samples-metadata-import/components/SampleMetadataImportMapHeaders.jsx, src/main/webapp/resources/js/pages/projects/samples-metadata-import/components/SampleMetadataImportReview.jsx, src/main/webapp/resources/js/pages/projects/samples-metadata-import/components/SampleMetadataImportUploadFile.jsx, src/main/webapp/resources/js/pages/projects/samples-metadata-import/index.js, src/main/webapp/yarn.lock
This is an start of a full update from `reach-router` to `react-router`.  Since `react-router-dom` was already used on the new metadata uploader page, I updated to use the new v6 API.
Related to #1108 
=> Upgrade react router v6

doc/administrator/faq/index.md, src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/3.7.0/sample-sequencingobject.xml
Fix liquibase changeset so that devs/admins don't have to remove `only_full_group_by` from `sql_mode` as this is default with newer version of mysql and mariadb.
=> Fix GROUP BY error caused by sql_mode=only_full_group_by

src/main/webapp/resources/js/contexts/UserGroupsContext.js, src/main/webapp/resources/js/pages/UserGroupsPage/index.js
Fixes issue where the user groups page does not load for a regular user.  This was caused by an upgrade to react-router-dom from reach-router.
N/A
=> Fixed user group not displaying

CHANGELOG.md, pom.xml
Upgraded to Spring Boot 2.6.6 which fixes CVE-2022-22965.
=> HOTFIX: CVE-2022-22965

src/main/java/ca/corefacility/bioinformatics/irida/ria/web/linelist/LineListController.java, src/main/webapp/resources/js/pages/projects/linelist/components/Table/Table.jsx
Fixed bug where line list page would hang on Loading 0 of n samples if there was no sample metadata or no samples in a project.
**To test broken functionality:**
1) Checkout `develpoment` branch
2) Create new project and add sample
3) Visit the line list page. It should hang on the `Loading 0 of n Samples` with a `NullPointerException` in the console
4) Try with a project with no samples as well. Should have the same behaviour as above
**To test fixed functionality:**
1) Checkout this branch
2) Create new project and add sample
3) Visit the line list page. The page should now load without hanging or console errors.
4) Try with a project with …
=> Fixed line list loading

CHANGELOG.md, UPGRADING.md, doc/administrator/web/config/irida.conf, src/main/java/ca/corefacility/bioinformatics/irida/processing/impl/AutomatedAnalysisFileProcessor.java, src/main/resources/ca/corefacility/bioinformatics/irida/config/workflows.properties, src/main/resources/i18n/messages.properties
This sets the default status of the built-in `SISTR_TYPING` and `MLST_MENTALIST` pipelines to disabled. A disabled pipeline still exists in IRIDA, but it is not possible to run it. For SISTR, we are switching to the plugin version of the pipeline. For Mentalist we are deprecating the pipeline.
The code for disabling pipelines already existed. This mainly changes the default pipelines which are disabled (above). These can be overridden with the configuration property `irida.workflow.types.disabled` (i.e., to re-enable these pipelines, you can set this property to blank in the `/etc/irida/irida.conf` file).
One small bit of code change that was required was with automated pipelines for a project. Previously, we were disabling automated pipelines if a new version of a pipeline was released. …
=> Disable built-in SISTR and Mentalist pipelines

src/main/webapp/pages/index.html, src/main/webapp/pages/projects/projects.html, src/main/webapp/pages/sequencing-runs/index.html, src/main/webapp/pages/template/page.html, src/main/webapp/pages/user/account.html, src/main/webapp/resources/css/app.css, src/main/webapp/resources/js/components/page/NarrowPageWrapper.jsx, src/main/webapp/resources/js/components/page/PageWrapper.jsx, src/main/webapp/resources/js/components/page/styles.css, src/main/webapp/resources/js/pages/user/components/UserAccountLayout.jsx, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectSamplesPage.java
Fixes the need to add `background-color: hsl(216deg 20% 95%);` to the body of pages that use the `NarrowPageWrapper` or the `PageWrapper`.  This is done by importing a small CSS file into the layout component.  Do not need to use `styled-components` for this since you need direct access to the `body` tag and we have been having some issues with conflicts with multiple instances of `styled-components`.
*   [ ] Tests added (or description of how to test) …
=> Fixes issue with full color bleeds on layout pages

CHANGELOG.md, src/main/webapp/.eslintrc.js, src/main/webapp/package.json, src/main/webapp/resources/js/apis/cart/cart.js, src/main/webapp/resources/js/apis/files/files.js, src/main/webapp/resources/js/pages/user/components/UserChangePasswordForm.jsx, src/main/webapp/resources/js/pages/user/components/UserTable.jsx, src/main/webapp/resources/js/utilities/html-utilities.js
Added `lint` command to yarn scripts to facilitate faster and easier linting of js/ts code.  
Added eslint rule to check for object and array restructuring.  
Fixed **some** of the eslint errors.
=> Eslint Updates

CHANGELOG.md, src/main/webapp/.eslintrc.js, src/main/webapp/package.json, src/main/webapp/yarn.lock
See https://prettier.io/docs/en/integrating-with-linters.html
=> Updated eslint prettier config so they work better together

CHANGELOG.md, src/main/java/ca/corefacility/bioinformatics/irida/config/services/scheduled/ProjectSyncScheduledTaskConfig.java, src/main/java/ca/corefacility/bioinformatics/irida/service/remote/ProjectSynchronizationService.java, src/test/java/ca/corefacility/bioinformatics/irida/service/ProjectSynchronizationServiceTest.java
When syncing a sample delete previously synced sequencing objects and assemblies that no longer exist on the source.
=> Remove synced files that have been remotely deleted

CHANGELOG.md, src/main/java/ca/corefacility/bioinformatics/irida/model/project/Project.java, src/main/resources/ca/corefacility/bioinformatics/irida/sql/required-data.sql, src/main/webapp/resources/js/pages/projects/settings/components/DeleteProject.jsx, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectDeletePage.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectDeletePageIT.java, src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/ProjectsPageIT.xml
A notification with "Internal Error" pops up when a user tries to delete a project with project subscriptions.
This is due to the following:
Caused by: java.sql.SQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`irida_test`.`project_subscription`, CONSTRAINT `FK_PROJECT_SUBSCRIPTION_PROJECT` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`))
N/A
=> Fix delete project

src/main/webapp/resources/js/pages/projects/redux/samplesSlice.js, src/main/webapp/resources/js/pages/projects/samples/components/SamplesTable.jsx, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectSamplesPage.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectSamplesPageIT.java
There appears to be a change in the pay redux toolkit returns stat within a slice `addCase` callback, it now appears to return a proxy to the state, which was causing issues comparing objects.   This was causing sample selection across pages to become broken on the project samples table.
I fixed this issue by moving the logic up into an `createAsyncThunk` function where I can get the state directly using the `getState` method.  Instead of just strinifying the object, I updated it to use the lodash isEqual function.
N/A
~* [ ] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.~ 
- Not required as this is a development issue.
~* [ ] User documentation updated for UI or …
=> Fixes issue where sample selection is not maintained between table pages.

CHANGELOG.md, doc/developer/rest/index.md, src/main/java/ca/corefacility/bioinformatics/irida/web/controller/api/json/DateJson.java, src/main/resources/i18n/messages.properties, src/main/webapp/pages/projects/export/ncbi.html, src/main/webapp/pages/samples/sample_files.html, src/main/webapp/pages/templates/_sequenceFile.html, src/main/webapp/resources/js/pages/projects/linelist/components/Table/Table.jsx, src/main/webapp/resources/js/utilities/date-utilities.js, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/samples/SampleFilesPage.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/samples/SampleFilesPageIT.java, src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/samples/SamplePagesIT.xml
`YYYY` year format is actually week year which results in the incorrect calendar year being shown.
i.e. date is December 31, 2021, when using `YYYY` year is displayed as 2022 instead of 2021.
This is due to the last day of that week being in 2022. (i.e. January 1, 2022 is Saturday which is the last day of that week).
=> fix: update year formatting from week year to calendar year

CHANGELOG.md, src/main/resources/application.properties
Set async request timeout to 60 minutes, to allow large file exports to work on the project samples page.
=> fix: large async downloads

CHANGELOG.md, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysisAjaxController.java, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/dto/AnalysisDetails.java, src/main/webapp/resources/js/contexts/AnalysisDetailsContext.js, src/main/webapp/resources/js/pages/analysis/components/settings/AnalysisShare.jsx, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/analysis/AnalysisDetailsPageIT.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/analysis/AnalysisDetailsPage.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/analysis/AnalysisAjaxControllerTest.java, src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysisAdminView.xml
Updated logic to not allow project collaborators to see the `Save results to samples` section within the analysis results.
**Project Manager**
**Project User**
Fixes #1325 
=> Fixed analysis results manage results

CHANGELOG.md, src/main/webapp/resources/js/apis/cart/cart.ts, src/main/webapp/resources/js/apis/samples/samples.ts, src/main/webapp/resources/js/components/samples/SampleDetailViewer.tsx, src/main/webapp/resources/js/components/samples/components/SampleDetailsModal.tsx, src/main/webapp/resources/js/components/samples/components/SampleDetailsWrapper.tsx, src/main/webapp/resources/js/components/samples/components/ViewerHeader.tsx, src/main/webapp/resources/js/components/samples/sampleSlice.ts, src/main/webapp/resources/js/pages/cart/components/SampleRenderer.jsx, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/CartPageIT.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/components/SampleDetailsViewer.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectSamplesPage.java
Fixed bug with sample details viewer which would still display a `Add to Cart` button to if the modal was closed and relaunched after the sample was added to the cart from the viewer.
Steps to reproduce before fix:
1) Add sample to project
2) Launch sample details viewer by clicking on the sample name in the project samples table
3) Click the `Add to Cart` button. Should now display the `Remove from Cart` button
4) Close the viewer
5) Relaunch the details viewer for the same sample
6) You should see a `Add to Cart` button
To test fix:
1) Add sample to project
2) Launch sample details viewer by clicking on the sample name in the project …
=> Hotfix: Sample details modal add/remove to/from cart

build.gradle.kts, settings.gradle.kts, src/main/webapp/package.json, src/main/webapp/pnpm-lock.yaml
`buildWebapp` task now only runs when inputs change (src dir or packages), or when outputs change (output directory is different due to running `startWebapp` task). This should now speedup starting the development server when no frontend changes have been made.
=> BUILD: gradle buildWebapp enhancements

CHANGELOG.md, doc/developer/getting-started/index.md
Fixed some broken links in the developer documentation. Also fixed up some info in the CHANGELOG.
To test, you can build the docs as follows:
```bash
cd doc
bundle exec jekyll serve --host 0.0.0.0 --port 3000
```
Now you should be able to go to http://localhost:3000/irida-documentation and view the documentation.
You can remove the `--host 0.0.0.0 --port 3000` and it defaults to http://localhost:4000/irida-documentation
None.
=> Fixed broken links in documentation

src/main/resources/i18n/messages.properties, src/main/webapp/resources/js/pages/projects/samples-metadata-import/components/SampleMetadataImportReview.tsx
N/A
* ~[ ] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.~
=> Metadata uploader progress bar

CHANGELOG.md, src/main/java/ca/corefacility/bioinformatics/irida/exceptions/IridaOAuthException.java, src/main/java/ca/corefacility/bioinformatics/irida/repositories/remote/resttemplate/IridaOAuthErrorHandler.java, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/ajax/RemoteAPIAjaxController.java, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIRemoteAPIService.java, src/main/resources/i18n/messages.properties, src/main/webapp/resources/js/apis/remote-api/remote-api.js, src/main/webapp/resources/js/components/remote-api/CreateRemoteProjectSyncForm.jsx, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectSyncPage.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/remoteapi/RemoteAPIsPage.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectSyncPageIT.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectsPageIT.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/services/UIRemoteAPIServiceTest.java, src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/ProjectsPageIT.xml
Updated to display error message if setting url manually for sync new remote project and the server returns an error (such as unauthorized, forbidden, not found, etc)
**To test:**
1) Create a project as user A and note the project ID (will use this is step 6)
2) Login as user B
3) From the `Projects` dropdown select `Synchronize Remote Project`
4) Select a project from the drop down
5) Click the checkbox for `Set URL Manually`
6) Enter in the url `http://IP_ADDRESS:PORT/api/projects/PROJECT_ID`
7) Click the `Create Synchronized Project` button
8) The URL input box should have an error underneath (access is denied)
To test not found error …
=> HOTFIX: display synchronize new remote project url errors

CHANGELOG.md, src/main/webapp/resources/js/pages/projects/ncbi/create/CreateNcbiExport.tsx, src/main/webapp/resources/js/pages/projects/ncbi/create/CreateNcbiSampleDetails.tsx, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/NcbiExportPage.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/NcbiExportPageIT.java
The NCBI export page was failing to actually export samples :(. **This is lousy**.
What was wrong:
- Files were not sent as a required field.  This has been updated now. 
- Sample field values were not properly being sent.  The structure of the field was `field: {value: VALUE}`, and was attempting to send it as such.  This was fixed by getting the actual value and sending it.
To test:
1. Select samples (that have files) from the project samples page.
2. From the menu above the table: Export > Upload to NCBI SRA
3. Fill in the fields for the submission details.
4. Select sample default values or fill in values for each sample.
5. To check the files, open up a sample collapsed region and select then deselect a file.  A message should be displayed underneath them that shows the error …
=> HOTFIX: Fixed issue with export file and instrument model using the NCBI Exporter

CHANGELOG.md, build.gradle.kts, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UINcbiService.java, src/main/resources/ca/corefacility/bioinformatics/irida/export/ncbi.xml, src/main/webapp/resources/js/components/ncbi/details/utils.tsx, src/main/webapp/resources/js/pages/projects/ncbi/create/CreateNcbiExport.tsx, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/NcbiExportPage.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/NcbiExportsListingPage.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/NcbiExportPageIT.java, src/test/java/ca/corefacility/bioinformatics/irida/service/export/ExportUploadServiceTest.java, src/test/resources/files/ncbi-export-test/example-ncbi.xml
Fixes issue with NCBI Exports failing when picked up by background task. Changes `value` to `model` for `sample.instrumentModel.model`.
Fixes #1449
Fixes #1452
=> Fix NCBI Export

CHANGELOG.md, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/samples/SamplesAjaxController.java, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UISampleService.java, src/main/webapp/resources/js/apis/samples/samples.ts, src/main/webapp/resources/js/components/samples/components/SampleMetadata.tsx
The sample modified date was not being updated when metadata was deleted.
N/A
=> Fix for updating sample modified date when metadata is deleted

src/main/webapp/resources/js/components/samples/components/SampleFiles.tsx, src/main/webapp/resources/js/components/samples/sampleFilesSlice.ts
Fixed sample details viewer files not displaying after uploading and closing/reopening the modal. Cleaned it up to refetch the sample files after uploading rather than storing the files in the state (can't use invalidatetags since the upload functions aren't a part of the createapi).
**To test broken functionality**
1) Checkout the `development` branch
2) Create a project and add a sample
3) Launch the sample details viewer by clicking on the sample name and then click the files tab
4) Upload some files to the sample
5) Close the sample details viewer and then relaunch and click the files tab
6) The files list should be empty even though we …
=> Fixed sample details viewer files display

CHANGELOG.md, src/main/java/ca/corefacility/bioinformatics/irida/web/controller/api/projects/RESTProjectSamplesController.java, src/test/java/ca/corefacility/bioinformatics/irida/web/controller/test/integration/project/ProjectSamplesIT.java, src/test/java/ca/corefacility/bioinformatics/irida/web/controller/test/unit/projects/RESTProjectSamplesControllerTest.java
Added deprecated tag to getSampleBySequencerId
Added new api route getSampleBySampleName, which accepts a json dictionary with the property "sampleName"
N/A
=> deprecated getSampleBySequencerId, added getSampleBySampleName

CHANGELOG.md, src/main/java/ca/corefacility/bioinformatics/irida/repositories/sample/SampleRepositoryCustom.java, src/main/java/ca/corefacility/bioinformatics/irida/repositories/sample/SampleRepositoryImpl.java, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UISampleService.java, src/main/java/ca/corefacility/bioinformatics/irida/service/impl/GenomeAssemblyServiceImpl.java, src/main/java/ca/corefacility/bioinformatics/irida/service/impl/sample/SampleServiceImpl.java, src/main/java/ca/corefacility/bioinformatics/irida/service/remote/ProjectSynchronizationService.java, src/main/java/ca/corefacility/bioinformatics/irida/service/sample/SampleService.java, src/main/java/ca/corefacility/bioinformatics/irida/web/controller/api/samples/RESTSampleSequenceFilesController.java, src/test/java/ca/corefacility/bioinformatics/irida/service/ProjectHashingServiceIT.java, src/test/java/ca/corefacility/bioinformatics/irida/service/ProjectSynchronizationServiceTest.java, src/test/java/ca/corefacility/bioinformatics/irida/service/impl/integration/sample/SampleServiceImplIT.java, src/test/java/ca/corefacility/bioinformatics/irida/service/impl/unit/sample/SampleServiceImplTest.java, src/test/java/ca/corefacility/bioinformatics/irida/web/controller/test/unit/samples/SampleSequenceFilesControllerTest.java
Fixed bug with default sequencing object and default genome assembly not being set to NULL when they are removed from a sample. Moved the setting of the default sequencing object and default genome assembly to `SampleService` and `GenomeAssemblyService` respectively
**To Test:**
1) On development branch, add a project and add a sample to the project
2) Launch the sample details viewer and click the files tab
3) Upload 2 paired end files to the sample
4) Set the second pair to be …
=> Set Default Sequencing Object/Genome Assembly to null when deleted

CHANGELOG.md, src/main/java/ca/corefacility/bioinformatics/irida/model/sample/Sample.java, src/main/webapp/resources/js/pages/projects/samples/components/RemoveModal.jsx, src/main/webapp/resources/js/pages/projects/samples/components/SamplesMenu.jsx, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/ProjectMembersPage.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/projects/ProjectSamplesPage.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectSamplesPageIT.java, src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/projects/ProjectSamplesPage.xml
Fixed bug with cascading deletes failing when attempting to remove a sample that had an analysis run on it.  Removing `cascade = CascadeType.ALL` allowed the cascade to work properly.  Also needed to update how the UI handled and error if a sample could not be removed.
**To Test:**
1.  Login as a user (fbristow works)
2.  Create a new project
3.  Create a sample in that project
4.  Add multiple files to the new sample
5.  Run the assembly and annotation pipeline (just needs to start not actually run)
6.  Go back to the project and remove the sample you created.
**To Test Error Notification:**
1.  Login as a user (fbristow works)
2.  Create a new project
3.  Create a sample in that project
4.  Add multiple files to the new sample
5.  Run the assembly and annotation pipeline (just needs to …
=> Fix remove sample error

CHANGELOG.md, build.gradle.kts, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIProjectSampleService.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectSampleMetadataImportPageIT.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/services/UIProjectSampleServiceTest.java, src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/projects/ProjectSampleMetadataView.xml
Fixing a bug where using the metadata uploader deleted exiting sample metadata. 
Fixes #1488.
=> Fix for metadata uploader overwriting existing data

CHANGELOG.md, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/pipelines/LaunchPipelinePage.java
Fixed a flaky part of the PipelinesPhylogenomicsPageIT#testPageSetup for saving modified pipeline parameters.
* Removed maximizing page size
* Added scrolling to the modified alert save button
* Cleaned up check to see if the modified alert is removed from the page.
N/A
=> test: Fix flaky PipelinesPhylogenomicsPageIT

CHANGELOG.md, src/main/resources/scripts/sequence-files/purge_sequence_files.py
Adding start and end dates to clean up scrip, as it might be used in a future scheduled cron job.
Fixes #1125.
=> Adding start and end dates to cleanup script

CHANGELOG.md, src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIProjectMembersService.java, src/main/webapp/resources/js/components/ant.design/PagedTable/PagedTable.jsx, src/main/webapp/resources/js/components/project-members/ProjectMembersTable.jsx, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/components/AntTable.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/pages/ProjectMembersPage.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectMembersPageIT.java, src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/services/UIProjectMembersServiceTest.java, src/test/resources/ca/corefacility/bioinformatics/irida/ria/web/ProjectsPageIT.xml
Fixed issue sorting by name on the project members table.  
When the method was called in the service it the sortColumn was set as `name` as that's what we have in the front end (combines the first and last name) which was retrieved on getting the members for the page originally. When we either sorted on the name column or switch pages it called the method with the sort params for the column as we set the sorter for it on the column in the front end code. When it went to do the order by on the query it was trying to get the name from the projectuserjoin which doesn't have a name column, neither does the User model, hence why if the column is name we sort on the first name for the user.
Link to the GitHub issue this pull request addresses using the `#issuenum` format. If it completes an …
=> Fixed sort on project members table

src/main/webapp/package.json, src/main/webapp/pnpm-lock.yaml
What did you change in this pull request? Provide a description of files changed, user interactions changed, etc. Include how to test your changes
Upgaded xlsx to "https://cdn.sheetjs.com/xlsx-0.20.3/xlsx-0.20.3.tgz"
=> chore(deps): Uprgaded xlsx to "https://cdn.sheetjs.com/xlsx-0.20.3/xlsx-0.20.3.tgz"

.github/workflows/ci-test.yml, .github/workflows/grype-scan.yml, .github/workflows/linting.yml, build.gradle.kts, settings.gradle.kts, src/test/java/ca/corefacility/bioinformatics/irida/service/impl/integration/SequencingObjectServiceImplIT.java
=> chore(deps): Upgrade java from 11 to 17

src/main/webapp/resources/js/pages/analysis/components/AnalysisTextPreview.jsx
This PR fixes a bug with analysis text preview not being able to set the loaded file size using `document.getElementId` due to changes with react useeffect hook in react 18. Updated to set a state variable instead and that is used by the UI to display the loaded file size.
Before fix:
After fix:
~* [ ] …
=> Fix: Analysis Text Output Preview
